# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import plugin_pb2 as plugin__pb2
except ImportError:
    import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginHostServiceStub:
    """1. 插件宿主生命周期服务 (运行在 Host 端)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/kanon.plugin.v1.PluginHostService/Ping',
                request_serializer=plugin__pb2.PingRequest.SerializeToString,
                response_deserializer=plugin__pb2.PingResponse.FromString,
                _registered_method=True)
        self.ReloadPluginConfig = channel.unary_unary(
                '/kanon.plugin.v1.PluginHostService/ReloadPluginConfig',
                request_serializer=plugin__pb2.ReloadPluginConfigRequest.SerializeToString,
                response_deserializer=plugin__pb2.ReloadPluginConfigResponse.FromString,
                _registered_method=True)
        self.GetPluginMeta = channel.unary_unary(
                '/kanon.plugin.v1.PluginHostService/GetPluginMeta',
                request_serializer=plugin__pb2.GetPluginMetaRequest.SerializeToString,
                response_deserializer=plugin__pb2.GetPluginMetaResponse.FromString,
                _registered_method=True)


class PluginHostServiceServicer:
    """1. 插件宿主生命周期服务 (运行在 Host 端)
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadPluginConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPluginMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginHostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=plugin__pb2.PingRequest.FromString,
                    response_serializer=plugin__pb2.PingResponse.SerializeToString,
            ),
            'ReloadPluginConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadPluginConfig,
                    request_deserializer=plugin__pb2.ReloadPluginConfigRequest.FromString,
                    response_serializer=plugin__pb2.ReloadPluginConfigResponse.SerializeToString,
            ),
            'GetPluginMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPluginMeta,
                    request_deserializer=plugin__pb2.GetPluginMetaRequest.FromString,
                    response_serializer=plugin__pb2.GetPluginMetaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kanon.plugin.v1.PluginHostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kanon.plugin.v1.PluginHostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginHostService:
    """1. 插件宿主生命周期服务 (运行在 Host 端)
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.PluginHostService/Ping',
            plugin__pb2.PingRequest.SerializeToString,
            plugin__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadPluginConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.PluginHostService/ReloadPluginConfig',
            plugin__pb2.ReloadPluginConfigRequest.SerializeToString,
            plugin__pb2.ReloadPluginConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPluginMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.PluginHostService/GetPluginMeta',
            plugin__pb2.GetPluginMetaRequest.SerializeToString,
            plugin__pb2.GetPluginMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MessagePipelineServiceStub:
    """2. 消息与事件管道服务 (运行在 Host 端，Core 主动连接各 Host 端点发起调用)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnPreFilter = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnPreFilter',
                request_serializer=plugin__pb2.PipelineEventRequest.SerializeToString,
                response_deserializer=plugin__pb2.PreFilterResult.FromString,
                _registered_method=True)
        self.OnExecuteCommand = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnExecuteCommand',
                request_serializer=plugin__pb2.CommandExecuteRequest.SerializeToString,
                response_deserializer=plugin__pb2.CommandExecuteResponse.FromString,
                _registered_method=True)
        self.OnCallTool = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnCallTool',
                request_serializer=plugin__pb2.ToolCallRequest.SerializeToString,
                response_deserializer=plugin__pb2.ToolCallResponse.FromString,
                _registered_method=True)
        self.OnEvent = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnEvent',
                request_serializer=plugin__pb2.EventNotification.SerializeToString,
                response_deserializer=plugin__pb2.EventAck.FromString,
                _registered_method=True)
        self.OnDeliverMessage = channel.unary_unary(
                '/kanon.plugin.v1.MessagePipelineService/OnDeliverMessage',
                request_serializer=plugin__pb2.DeliverMessageRequest.SerializeToString,
                response_deserializer=plugin__pb2.DeliverMessageResponse.FromString,
                _registered_method=True)


class MessagePipelineServiceServicer:
    """2. 消息与事件管道服务 (运行在 Host 端，Core 主动连接各 Host 端点发起调用)
    """

    def OnPreFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnCallTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnDeliverMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagePipelineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnPreFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPreFilter,
                    request_deserializer=plugin__pb2.PipelineEventRequest.FromString,
                    response_serializer=plugin__pb2.PreFilterResult.SerializeToString,
            ),
            'OnExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.OnExecuteCommand,
                    request_deserializer=plugin__pb2.CommandExecuteRequest.FromString,
                    response_serializer=plugin__pb2.CommandExecuteResponse.SerializeToString,
            ),
            'OnCallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.OnCallTool,
                    request_deserializer=plugin__pb2.ToolCallRequest.FromString,
                    response_serializer=plugin__pb2.ToolCallResponse.SerializeToString,
            ),
            'OnEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.OnEvent,
                    request_deserializer=plugin__pb2.EventNotification.FromString,
                    response_serializer=plugin__pb2.EventAck.SerializeToString,
            ),
            'OnDeliverMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.OnDeliverMessage,
                    request_deserializer=plugin__pb2.DeliverMessageRequest.FromString,
                    response_serializer=plugin__pb2.DeliverMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kanon.plugin.v1.MessagePipelineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kanon.plugin.v1.MessagePipelineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessagePipelineService:
    """2. 消息与事件管道服务 (运行在 Host 端，Core 主动连接各 Host 端点发起调用)
    """

    @staticmethod
    def OnPreFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnPreFilter',
            plugin__pb2.PipelineEventRequest.SerializeToString,
            plugin__pb2.PreFilterResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnExecuteCommand',
            plugin__pb2.CommandExecuteRequest.SerializeToString,
            plugin__pb2.CommandExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnCallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnCallTool',
            plugin__pb2.ToolCallRequest.SerializeToString,
            plugin__pb2.ToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnEvent',
            plugin__pb2.EventNotification.SerializeToString,
            plugin__pb2.EventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnDeliverMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.MessagePipelineService/OnDeliverMessage',
            plugin__pb2.DeliverMessageRequest.SerializeToString,
            plugin__pb2.DeliverMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BotApiServiceStub:
    """3. 核心 API 服务 (运行在 Core 端，监听 core.sock / loopback，Host 主动连接调用)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterHost = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/RegisterHost',
                request_serializer=plugin__pb2.RegisterHostRequest.SerializeToString,
                response_deserializer=plugin__pb2.RegisterHostResponse.FromString,
                _registered_method=True)
        self.IngestEvent = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/IngestEvent',
                request_serializer=plugin__pb2.IngestEventRequest.SerializeToString,
                response_deserializer=plugin__pb2.IngestEventResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/SendMessage',
                request_serializer=plugin__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=plugin__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.RequestLLM = channel.unary_stream(
                '/kanon.plugin.v1.BotApiService/RequestLLM',
                request_serializer=plugin__pb2.LLMRequest.SerializeToString,
                response_deserializer=plugin__pb2.LLMChunk.FromString,
                _registered_method=True)
        self.SetStorage = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/SetStorage',
                request_serializer=plugin__pb2.SetStorageRequest.SerializeToString,
                response_deserializer=plugin__pb2.SetStorageResponse.FromString,
                _registered_method=True)
        self.GetStorage = channel.unary_unary(
                '/kanon.plugin.v1.BotApiService/GetStorage',
                request_serializer=plugin__pb2.GetStorageRequest.SerializeToString,
                response_deserializer=plugin__pb2.GetStorageResponse.FromString,
                _registered_method=True)


class BotApiServiceServicer:
    """3. 核心 API 服务 (运行在 Core 端，监听 core.sock / loopback，Host 主动连接调用)
    """

    def RegisterHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestLLM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterHost': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterHost,
                    request_deserializer=plugin__pb2.RegisterHostRequest.FromString,
                    response_serializer=plugin__pb2.RegisterHostResponse.SerializeToString,
            ),
            'IngestEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestEvent,
                    request_deserializer=plugin__pb2.IngestEventRequest.FromString,
                    response_serializer=plugin__pb2.IngestEventResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=plugin__pb2.SendMessageRequest.FromString,
                    response_serializer=plugin__pb2.SendMessageResponse.SerializeToString,
            ),
            'RequestLLM': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestLLM,
                    request_deserializer=plugin__pb2.LLMRequest.FromString,
                    response_serializer=plugin__pb2.LLMChunk.SerializeToString,
            ),
            'SetStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStorage,
                    request_deserializer=plugin__pb2.SetStorageRequest.FromString,
                    response_serializer=plugin__pb2.SetStorageResponse.SerializeToString,
            ),
            'GetStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStorage,
                    request_deserializer=plugin__pb2.GetStorageRequest.FromString,
                    response_serializer=plugin__pb2.GetStorageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kanon.plugin.v1.BotApiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kanon.plugin.v1.BotApiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BotApiService:
    """3. 核心 API 服务 (运行在 Core 端，监听 core.sock / loopback，Host 主动连接调用)
    """

    @staticmethod
    def RegisterHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/RegisterHost',
            plugin__pb2.RegisterHostRequest.SerializeToString,
            plugin__pb2.RegisterHostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/IngestEvent',
            plugin__pb2.IngestEventRequest.SerializeToString,
            plugin__pb2.IngestEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/SendMessage',
            plugin__pb2.SendMessageRequest.SerializeToString,
            plugin__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/RequestLLM',
            plugin__pb2.LLMRequest.SerializeToString,
            plugin__pb2.LLMChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/SetStorage',
            plugin__pb2.SetStorageRequest.SerializeToString,
            plugin__pb2.SetStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kanon.plugin.v1.BotApiService/GetStorage',
            plugin__pb2.GetStorageRequest.SerializeToString,
            plugin__pb2.GetStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
