//! Platform adapter management and data-plane ingest routes.
//!
//! - `GET /api/v1/adapters` — the adapter catalog: built-in adapters plus every plugin whose
//!   manifest declares a platform, so a console can show which platforms this node can serve.
//! - `POST /api/v1/adapters/{platform}/ingest` — the HTTP data-plane entry point. External
//!   systems (webhooks, bridges, frontends) submit user messages here and receive a Fast-ACK
//!   reply; the message then travels the normal pipeline (PreFilter → command → LLM → outbound).
//!
//! Ingest is deliberately *not* merged with `POST /api/v1/chat/completions`: the latter is a
//! debug console that answers the caller, while this endpoint is fire-and-forget ingress whose
//! answer is delivered later through the platform's outbound adapter.

use axum::Json;
use axum::Router;
use axum::body::Bytes;
use axum::extract::{Path, State};
use axum::http::{HeaderMap, StatusCode};
use axum::routing::{get, post};
use kanon_core::{AdapterRoute, IngestError};
use kanon_proto::v1::{IngestEventRequest, PipelineEventRequest};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use crate::error::ApiError;
use crate::state::ApiState;

/// Registers adapter routes.
pub fn routes() -> Router<ApiState> {
    Router::new()
        .route("/api/v1/adapters", get(list_adapters))
        .route("/api/v1/adapters/:platform/ingest", post(ingest_event))
}

/// Adapter catalog payload.
#[derive(Debug, Serialize)]
pub struct AdapterCatalog {
    /// Total number of adapters (built-in and plugin).
    pub total: usize,
    /// Adapter descriptors, sorted by platform.
    pub adapters: Vec<kanon_core::AdapterDescriptor>,
}

/// Inbound message submitted by an external platform bridge.
#[derive(Debug, Deserialize)]
pub struct IngestRequest {
    /// Channel the message was sent in.
    pub channel_id: String,
    /// User that authored the message.
    pub sender_id: String,
    /// Message text.
    pub text: String,
    /// Optional caller-supplied event identifier; generated by the core when omitted.
    #[serde(default)]
    pub event_id: Option<String>,
    /// Optional free-form metadata forwarded to plugins.
    #[serde(default)]
    pub metadata: Option<Map<String, Value>>,
}

/// Fast-ACK acknowledgement of an accepted inbound message.
#[derive(Debug, Serialize)]
pub struct IngestAccepted {
    /// Always `true`; a rejected message is reported through an error status instead.
    pub accepted: bool,
    /// Identifier assigned to the accepted event.
    pub event_id: String,
    /// Platform the event was attributed to.
    pub platform: String,
}

/// Lists every platform adapter this node can serve.
async fn list_adapters(State(state): State<ApiState>) -> Json<AdapterCatalog> {
    let adapters = state.supervisor().adapter_catalog().await;

    Json(AdapterCatalog {
        total: adapters.len(),
        adapters,
    })
}

/// Accepts an inbound message for a platform and enqueues it into the core pipeline.
///
/// The platform must resolve to a registered adapter (built-in or plugin); accepting messages for
/// an unserved platform would create conversations that can never be answered.
/// When the target adapter configures authentication (e.g. Webhook HMAC-SHA256), the signature
/// is verified against the raw request body before enqueuing.
async fn ingest_event(
    State(state): State<ApiState>,
    Path(platform): Path<String>,
    headers: HeaderMap,
    body_bytes: Bytes,
) -> Result<(StatusCode, Json<IngestAccepted>), ApiError> {
    let platform = platform.trim().to_string();
    if platform.is_empty() {
        return Err(ApiError::BadRequest(
            "Path parameter 'platform' must not be empty".to_string(),
        ));
    }

    let route = state
        .supervisor()
        .resolve_adapter(&platform)
        .await
        .ok_or_else(|| {
            ApiError::NotFound(format!("No adapter is registered for platform '{platform}'"))
        })?;

    // Extract signature header if present (supports X-Hub-Signature-256, X-Kanon-Signature, X-Signature-256)
    let signature = headers
        .get("x-hub-signature-256")
        .or_else(|| headers.get("x-kanon-signature"))
        .or_else(|| headers.get("x-signature-256"))
        .and_then(|val| val.to_str().ok());

    // Verify inbound authentication if the adapter enforces it (e.g. HMAC-SHA256)
    if let AdapterRoute::Builtin(ref adapter) = route {
        adapter.verify_inbound(signature, &body_bytes).map_err(|err| match err {
            kanon_core::AdapterError::Authentication { reason, .. } => {
                ApiError::Unauthorized(reason)
            }
            other => ApiError::BadRequest(other.to_string()),
        })?;
    }

    // Parse the JSON request body
    let body: IngestRequest = serde_json::from_slice(&body_bytes).map_err(|err| {
        ApiError::BadRequest(format!("Failed to parse request JSON body: {err}"))
    })?;

    if body.channel_id.trim().is_empty() {
        return Err(ApiError::BadRequest(
            "Field 'channel_id' must not be empty".to_string(),
        ));
    }
    if body.sender_id.trim().is_empty() {
        return Err(ApiError::BadRequest(
            "Field 'sender_id' must not be empty".to_string(),
        ));
    }
    if body.text.trim().is_empty() {
        return Err(ApiError::BadRequest(
            "Field 'text' must not be empty".to_string(),
        ));
    }

    let ingress = state.ingress().ok_or_else(|| {
        ApiError::Unavailable(
            "This core was built without an ingest queue; inbound messages are disabled"
                .to_string(),
        )
    })?;

    let event_id = body
        .event_id
        .filter(|id| !id.trim().is_empty())
        .unwrap_or_else(generate_event_id);

    let request = IngestEventRequest {
        platform: platform.clone(),
        event: Some(PipelineEventRequest {
            event_id: event_id.clone(),
            platform: platform.clone(),
            channel_id: body.channel_id,
            sender_id: body.sender_id,
            raw_text: body.text,
            segments: Vec::new(),
            metadata: body
                .metadata
                .map(|map| kanon_llm::tool_router::json_to_prost_struct(&Value::Object(map)))
                .unwrap_or_default(),
        }),
    };

    // Fast-ACK: the enqueue is non-blocking, so a platform webhook never waits for LLM reasoning.
    ingress.try_ingest(request).map_err(|err| match err {
        IngestError::QueueFull => ApiError::Unavailable(
            "Ingest queue is full; the core is saturated and the message was rejected".to_string(),
        ),
        IngestError::Closed => {
            ApiError::Unavailable("Ingest queue is closed; the core is shutting down".to_string())
        }
    })?;

    Ok((
        StatusCode::ACCEPTED,
        Json(IngestAccepted {
            accepted: true,
            event_id,
            platform,
        }),
    ))
}

/// Generates a process-unique event identifier.
///
/// Uniqueness only needs to hold within one core process (the pipeline keys traces by it), so a
/// monotonic counter mixed with the start timestamp is sufficient and avoids a dependency on
/// heavyweight UUID generation.
fn generate_event_id() -> String {
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    static SEQUENCE: AtomicU64 = AtomicU64::new(0);

    let millis = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis() as u64)
        .unwrap_or_default();
    let sequence = SEQUENCE.fetch_add(1, Ordering::Relaxed);

    format!("evt-{millis:x}-{sequence:x}")
}
