//! Platform adapter management and data-plane ingest routes.
//!
//! - `GET /api/v1/adapters` — the adapter catalog: built-in adapters plus every plugin whose
//!   manifest declares a platform, so a console can show which platforms this node can serve.
//! - `POST /api/v1/adapters/{platform}/ingest` — the HTTP data-plane entry point. External
//!   systems (webhooks, bridges, frontends) submit user messages here and receive a Fast-ACK
//!   reply; the message then travels the normal pipeline (PreFilter → command → LLM → outbound).
//!
//! Ingest is deliberately *not* merged with `POST /api/v1/chat/completions`: the latter is a
//! debug console that answers the caller, while this endpoint is fire-and-forget ingress whose
//! answer is delivered later through the platform's outbound adapter.

use axum::Json;
use axum::Router;
use axum::body::Bytes;
use axum::extract::{Path, State};
use axum::http::{HeaderMap, StatusCode};
use axum::routing::{get, post};
use kanon_core::{AdapterRoute, IngestError};
use kanon_proto::v1::{IngestEventRequest, PipelineEventRequest};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use crate::error::ApiError;
use crate::state::ApiState;

pub fn routes() -> Router<ApiState> {
    Router::new()
        .route("/api/v1/adapters", get(list_adapters))
        .route("/api/v1/adapters/:platform/ingest", post(ingest_event))
        .route(
            "/api/v1/adapters/qqofficial/login/qr",
            post(qqofficial_login_qr),
        )
        .route(
            "/api/v1/adapters/qqofficial/login/poll",
            post(qqofficial_login_poll),
        )
}

/// Adapter catalog payload.
#[derive(Debug, Serialize)]
pub struct AdapterCatalog {
    /// Total number of adapters (built-in and plugin).
    pub total: usize,
    /// Adapter descriptors, sorted by platform.
    pub adapters: Vec<kanon_core::AdapterDescriptor>,
}

/// Inbound message submitted by an external platform bridge.
#[derive(Debug, Deserialize)]
pub struct IngestRequest {
    /// Channel the message was sent in.
    pub channel_id: String,
    /// User that authored the message.
    pub sender_id: String,
    /// Message text.
    pub text: String,
    /// Optional caller-supplied event identifier; generated by the core when omitted.
    #[serde(default)]
    pub event_id: Option<String>,
    /// Optional free-form metadata forwarded to plugins.
    #[serde(default)]
    pub metadata: Option<Map<String, Value>>,
}

/// Fast-ACK acknowledgement of an accepted inbound message.
#[derive(Debug, Serialize)]
pub struct IngestAccepted {
    /// Always `true`; a rejected message is reported through an error status instead.
    pub accepted: bool,
    /// Identifier assigned to the accepted event.
    pub event_id: String,
    /// Platform the event was attributed to.
    pub platform: String,
}

/// Lists every platform adapter this node can serve.
async fn list_adapters(State(state): State<ApiState>) -> Json<AdapterCatalog> {
    let adapters = state.supervisor().adapter_catalog().await;

    Json(AdapterCatalog {
        total: adapters.len(),
        adapters,
    })
}

/// Accepts an inbound message for a platform and enqueues it into the core pipeline.
///
/// The platform must resolve to a registered adapter (built-in or plugin); accepting messages for
/// an unserved platform would create conversations that can never be answered.
/// When the target adapter configures authentication (e.g. Webhook HMAC-SHA256), the signature
/// is verified against the raw request body before enqueuing.
async fn ingest_event(
    State(state): State<ApiState>,
    Path(platform): Path<String>,
    headers: HeaderMap,
    body_bytes: Bytes,
) -> Result<(StatusCode, Json<IngestAccepted>), ApiError> {
    let platform = platform.trim().to_string();
    if platform.is_empty() {
        return Err(ApiError::BadRequest(
            "Path parameter 'platform' must not be empty".to_string(),
        ));
    }

    let route = state
        .supervisor()
        .resolve_adapter(&platform)
        .await
        .ok_or_else(|| {
            ApiError::NotFound(format!("No adapter is registered for platform '{platform}'"))
        })?;

    // Extract signature header if present (supports X-Hub-Signature-256, X-Kanon-Signature, X-Signature-256)
    let signature = headers
        .get("x-hub-signature-256")
        .or_else(|| headers.get("x-kanon-signature"))
        .or_else(|| headers.get("x-signature-256"))
        .and_then(|val| val.to_str().ok());

    // Verify inbound authentication if the adapter enforces it (e.g. HMAC-SHA256)
    if let AdapterRoute::Builtin(ref adapter) = route {
        adapter.verify_inbound(signature, &body_bytes).map_err(|err| match err {
            kanon_core::AdapterError::Authentication { reason, .. } => {
                ApiError::Unauthorized(reason)
            }
            other => ApiError::BadRequest(other.to_string()),
        })?;
    }

    // Parse the JSON request body
    let body: IngestRequest = serde_json::from_slice(&body_bytes).map_err(|err| {
        ApiError::BadRequest(format!("Failed to parse request JSON body: {err}"))
    })?;

    if body.channel_id.trim().is_empty() {
        return Err(ApiError::BadRequest(
            "Field 'channel_id' must not be empty".to_string(),
        ));
    }
    if body.sender_id.trim().is_empty() {
        return Err(ApiError::BadRequest(
            "Field 'sender_id' must not be empty".to_string(),
        ));
    }
    if body.text.trim().is_empty() {
        return Err(ApiError::BadRequest(
            "Field 'text' must not be empty".to_string(),
        ));
    }

    let ingress = state.ingress().ok_or_else(|| {
        ApiError::Unavailable(
            "This core was built without an ingest queue; inbound messages are disabled"
                .to_string(),
        )
    })?;

    let event_id = body
        .event_id
        .filter(|id| !id.trim().is_empty())
        .unwrap_or_else(generate_event_id);

    let request = IngestEventRequest {
        platform: platform.clone(),
        event: Some(PipelineEventRequest {
            event_id: event_id.clone(),
            platform: platform.clone(),
            channel_id: body.channel_id,
            sender_id: body.sender_id,
            raw_text: body.text,
            segments: Vec::new(),
            metadata: body
                .metadata
                .map(|map| kanon_llm::tool_router::json_to_prost_struct(&Value::Object(map)))
                .unwrap_or_default(),
        }),
    };

    // Fast-ACK: the enqueue is non-blocking, so a platform webhook never waits for LLM reasoning.
    ingress.try_ingest(request).map_err(|err| match err {
        IngestError::QueueFull => ApiError::Unavailable(
            "Ingest queue is full; the core is saturated and the message was rejected".to_string(),
        ),
        IngestError::Closed => {
            ApiError::Unavailable("Ingest queue is closed; the core is shutting down".to_string())
        }
    })?;

    Ok((
        StatusCode::ACCEPTED,
        Json(IngestAccepted {
            accepted: true,
            event_id,
            platform,
        }),
    ))
}

/// Generates a process-unique event identifier.
///
/// Uniqueness only needs to hold within one core process (the pipeline keys traces by it), so a
/// monotonic counter mixed with the start timestamp is sufficient and avoids a dependency on
/// heavyweight UUID generation.
fn generate_event_id() -> String {
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    static SEQUENCE: AtomicU64 = AtomicU64::new(0);

    let millis = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis() as u64)
        .unwrap_or_default();
    let sequence = SEQUENCE.fetch_add(1, Ordering::Relaxed);

    format!("evt-{millis:x}-{sequence:x}")
}

/// Request payload for generating a QQ Official Bot QR code login task.
#[derive(Debug, Deserialize, Default)]
pub struct QqQrRequest {
    /// Optional bind host override (defaults to "q.qq.com").
    #[serde(default)]
    pub bind_host: Option<String>,
}

/// Response containing QR code metadata for QQ Official Bot authorization.
#[derive(Debug, Serialize, Deserialize)]
pub struct QqQrResponse {
    /// Unique task identifier for polling.
    pub task_id: String,
    /// Base64-encoded AES-256 GCM key for decrypting the credentials.
    pub bind_key: String,
    /// Direct authorization URL for Mobile QQ.
    pub qrcode_url: String,
    /// Suggested polling interval in seconds.
    pub poll_interval_seconds: u64,
}

/// Request payload for polling QQ Official Bot QR authorization status.
#[derive(Debug, Deserialize)]
pub struct QqPollRequest {
    /// Task identifier returned by `qqofficial_login_qr`.
    pub task_id: String,
    /// Base64-encoded AES-256 key matching the task.
    pub bind_key: String,
    /// Optional bind host override.
    #[serde(default)]
    pub bind_host: Option<String>,
    /// Whether to automatically persist and hot-reload credentials when completed.
    #[serde(default = "default_true")]
    pub auto_save: bool,
}

fn default_true() -> bool {
    true
}

/// Response returned from polling the QR authorization status.
#[derive(Debug, Serialize, Deserialize)]
pub struct QqPollResponse {
    /// Normalized authorization status: "pending", "created", "expired", or "error".
    pub status: String,
    /// Underlying numeric QR status from QQ API (0: none, 1: pending, 2: completed, 3: expired).
    pub qr_status: i64,
    /// Decrypted Bot AppID upon successful binding.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub appid: Option<String>,
    /// Decrypted Bot AppSecret upon successful binding.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    /// Whether credentials were saved to disk and hot-reloaded.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub saved: Option<bool>,
    /// Informational or error message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// Requests a new QR code binding task for QQ Official Bot credentials.
///
/// First attempts to delegate the creation to the running QQ Official plugin host over gRPC Tool Calling.
/// If the host process is not running or the tool is unavailable, falls back to direct HTTP communication
/// with the QQ OpenClaw binding backend.
async fn qqofficial_login_qr(
    State(state): State<ApiState>,
    Json(body): Json<QqQrRequest>,
) -> Result<Json<QqQrResponse>, ApiError> {
    const QQ_PLUGIN_ID: &str = "org.kanon.adapter.qqofficial";

    // Step 1: Delegate to running plugin host via gRPC Tool Calling if available
    if let Some(host) = state.supervisor().find_host_for_plugin(QQ_PLUGIN_ID).await {
        let args = serde_json::json!({
            "bind_host": body.bind_host,
        });
        let req = kanon_proto::v1::ToolCallRequest {
            call_id: generate_event_id(),
            tool_name: "qq_request_login_qr".to_string(),
            session_id: "system-login".to_string(),
            payload: Some(kanon_proto::v1::tool_call_request::Payload::StructuredArgs(
                kanon_llm::tool_router::json_to_prost_struct(&args).unwrap_or_default(),
            )),
        };
        if let Ok(resp) = host.on_call_tool(req).await {
            if resp.success {
                if let Some(kanon_proto::v1::tool_call_response::Payload::StructuredResult(res)) =
                    resp.payload
                {
                    let val = kanon_llm::tool_router::prost_struct_to_json(res);
                    if let Ok(qr_resp) = serde_json::from_value::<QqQrResponse>(val) {
                        return Ok(Json(qr_resp));
                    }
                }
            }
        }
    }

    // Step 2: Fallback to direct HTTP binding creation when plugin host is offline
    let raw_host = body.bind_host.as_deref().unwrap_or("q.qq.com");
    let scheme = if raw_host.starts_with("http://")
        || raw_host.contains("127.0.0.1")
        || raw_host.contains("localhost")
    {
        "http"
    } else {
        "https"
    };
    let bind_host = raw_host
        .trim_start_matches("https://")
        .trim_start_matches("http://")
        .trim_end_matches('/');

    let mut key_bytes = [0u8; 32];
    use ring::rand::SecureRandom;
    let rng = ring::rand::SystemRandom::new();
    rng.fill(&mut key_bytes)
        .map_err(|_| ApiError::Internal("Entropy generation failed".to_string()))?;

    use base64::Engine;
    let bind_key = base64::engine::general_purpose::STANDARD.encode(key_bytes);

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build()
        .map_err(|e| ApiError::Internal(e.to_string()))?;

    let url = format!("{scheme}://{bind_host}/lite/create_bind_task");
    let resp = client
        .post(&url)
        .header("Accept", "application/json")
        .header("User-Agent", "Mozilla/5.0 (compatible; KanonBot/0.1.0)")
        .json(&serde_json::json!({ "key": &bind_key, "bind_key": &bind_key }))
        .send()
        .await
        .map_err(|e| ApiError::Internal(format!("Failed to connect to QQ auth server: {e}")))?;

    let data: Value = resp
        .json()
        .await
        .map_err(|e| ApiError::Internal(format!("Failed to parse QQ auth response: {e}")))?;

    let task_id = data
        .get("data")
        .and_then(|d| d.get("task_id"))
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            let msg = data
                .get("msg")
                .or_else(|| data.get("message"))
                .and_then(|v| v.as_str())
                .unwrap_or("QQ auth server did not return task_id");
            ApiError::Internal(msg.to_string())
        })?
        .to_string();

    let qrcode_url =
        format!("https://{bind_host}/qqbot/openclaw/connect.html?task_id={task_id}&_wv=2");

    Ok(Json(QqQrResponse {
        task_id,
        bind_key,
        qrcode_url,
        poll_interval_seconds: 2,
    }))
}

/// Polls QQ Official Bot QR authorization status.
///
/// If credentials are ready and `auto_save` is enabled, the AppID and AppSecret are
/// automatically persisted to the plugin's configuration file and hot-reloaded into the running host.
async fn qqofficial_login_poll(
    State(state): State<ApiState>,
    Json(body): Json<QqPollRequest>,
) -> Result<Json<QqPollResponse>, ApiError> {
    const QQ_PLUGIN_ID: &str = "org.kanon.adapter.qqofficial";

    // Step 1: Delegate to running plugin host via gRPC Tool Calling if available
    if let Some(host) = state.supervisor().find_host_for_plugin(QQ_PLUGIN_ID).await {
        let args = serde_json::json!({
            "task_id": body.task_id,
            "bind_key": body.bind_key,
        });
        let req = kanon_proto::v1::ToolCallRequest {
            call_id: generate_event_id(),
            tool_name: "qq_poll_login_result".to_string(),
            session_id: "system-login".to_string(),
            payload: Some(kanon_proto::v1::tool_call_request::Payload::StructuredArgs(
                kanon_llm::tool_router::json_to_prost_struct(&args).unwrap_or_default(),
            )),
        };
        if let Ok(resp) = host.on_call_tool(req).await {
            if resp.success {
                if let Some(kanon_proto::v1::tool_call_response::Payload::StructuredResult(res)) =
                    resp.payload
                {
                    let val = kanon_llm::tool_router::prost_struct_to_json(res);
                    if let Ok(mut poll_resp) = serde_json::from_value::<QqPollResponse>(val) {
                        if poll_resp.status == "created" && body.auto_save {
                            if let (Some(appid), Some(secret)) =
                                (&poll_resp.appid, &poll_resp.secret)
                            {
                                let _ =
                                    save_and_reload_qq_credentials(&state, appid, secret).await;
                                poll_resp.saved = Some(true);
                            }
                        }
                        return Ok(Json(poll_resp));
                    }
                }
            }
        }
    }

    // Step 2: Fallback to direct HTTP polling when plugin host is offline
    let raw_host = body.bind_host.as_deref().unwrap_or("q.qq.com");
    let scheme = if raw_host.starts_with("http://")
        || raw_host.contains("127.0.0.1")
        || raw_host.contains("localhost")
    {
        "http"
    } else {
        "https"
    };
    let bind_host = raw_host
        .trim_start_matches("https://")
        .trim_start_matches("http://")
        .trim_end_matches('/');

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build()
        .map_err(|e| ApiError::Internal(e.to_string()))?;

    let url = format!("{scheme}://{bind_host}/lite/poll_bind_result");
    let resp = client
        .post(&url)
        .header("Accept", "application/json")
        .header("User-Agent", "Mozilla/5.0 (compatible; KanonBot/0.1.0)")
        .json(&serde_json::json!({ "task_id": &body.task_id }))
        .send()
        .await
        .map_err(|e| ApiError::Internal(format!("Failed to connect to QQ auth server: {e}")))?;

    let data: Value = resp
        .json()
        .await
        .map_err(|e| ApiError::Internal(format!("Failed to parse QQ poll response: {e}")))?;

    let inner = data.get("data").cloned().unwrap_or(Value::Null);
    let raw_status = inner.get("status").and_then(|s| s.as_i64()).unwrap_or(0);

    match raw_status {
        2 => {
            let appid = inner
                .get("bot_appid")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .trim()
                .to_string();
            let enc_secret = inner
                .get("bot_encrypt_secret")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .trim();

            if appid.is_empty() || enc_secret.is_empty() {
                return Ok(Json(QqPollResponse {
                    status: "error".to_string(),
                    qr_status: raw_status,
                    appid: None,
                    secret: None,
                    saved: None,
                    message: Some("Authorization completed but missing credentials".to_string()),
                }));
            }

            match decrypt_qq_secret(enc_secret, &body.bind_key) {
                Ok(secret) => {
                    let mut saved = false;
                    if body.auto_save {
                        saved = save_and_reload_qq_credentials(&state, &appid, &secret)
                            .await
                            .is_ok();
                    }
                    Ok(Json(QqPollResponse {
                        status: "created".to_string(),
                        qr_status: raw_status,
                        appid: Some(appid),
                        secret: Some(secret),
                        saved: Some(saved),
                        message: None,
                    }))
                }
                Err(err) => Ok(Json(QqPollResponse {
                    status: "error".to_string(),
                    qr_status: raw_status,
                    appid: None,
                    secret: None,
                    saved: None,
                    message: Some(format!("Failed to decrypt secret: {err}")),
                })),
            }
        }
        3 => Ok(Json(QqPollResponse {
            status: "expired".to_string(),
            qr_status: raw_status,
            appid: None,
            secret: None,
            saved: None,
            message: Some("QR code expired".to_string()),
        })),
        _ => Ok(Json(QqPollResponse {
            status: "pending".to_string(),
            qr_status: raw_status,
            appid: None,
            secret: None,
            saved: None,
            message: None,
        })),
    }
}

/// Decrypts the QQ bot AppSecret returned from QR binding using AES-256-GCM.
fn decrypt_qq_secret(encrypted_b64: &str, bind_key_b64: &str) -> Result<String, String> {
    use base64::Engine;
    let key_bytes = base64::engine::general_purpose::STANDARD
        .decode(bind_key_b64)
        .map_err(|e| format!("Base64 decode key failed: {e}"))?;
    let raw = base64::engine::general_purpose::STANDARD
        .decode(encrypted_b64)
        .map_err(|e| format!("Base64 decode secret failed: {e}"))?;

    if key_bytes.len() != 32 {
        return Err(format!(
            "Invalid key length: expected 32, got {}",
            key_bytes.len()
        ));
    }
    if raw.len() <= 28 {
        return Err(format!("Invalid ciphertext length: {}", raw.len()));
    }

    let (nonce_bytes, in_out) = raw.split_at(12);
    let mut buffer = in_out.to_vec();

    use ring::aead::{AES_256_GCM, LessSafeKey, Nonce, UnboundKey};
    let unbound = UnboundKey::new(&AES_256_GCM, &key_bytes)
        .map_err(|_| "Failed to initialize unbound key".to_string())?;
    let key = LessSafeKey::new(unbound);
    let nonce =
        Nonce::try_assume_unique_for_key(nonce_bytes).map_err(|_| "Invalid nonce".to_string())?;

    let plaintext = key
        .open_in_place(nonce, ring::aead::Aad::empty(), &mut buffer)
        .map_err(|_| "AES-GCM decryption failed: tag mismatch".to_string())?;

    String::from_utf8(plaintext.to_vec()).map_err(|e| format!("UTF-8 decoding failed: {e}"))
}

/// Persists QQ Official Bot credentials to disk and triggers an in-process hot reload.
async fn save_and_reload_qq_credentials(
    state: &ApiState,
    appid: &str,
    secret: &str,
) -> Result<(), ApiError> {
    const QQ_PLUGIN_ID: &str = "org.kanon.adapter.qqofficial";
    let store = state.config_store().clone();
    let mut config = store
        .load(QQ_PLUGIN_ID)
        .unwrap_or_else(|_| serde_json::json!({}));
    if !config.is_object() {
        config = serde_json::json!({});
    }
    config["appid"] = serde_json::Value::String(appid.to_string());
    config["secret"] = serde_json::Value::String(secret.to_string());

    let plugin_id = QQ_PLUGIN_ID.to_string();
    let cfg_clone = config.clone();
    tokio::task::spawn_blocking(move || store.store(&plugin_id, &cfg_clone))
        .await
        .map_err(|err| ApiError::Internal(format!("Persistence task failed: {err}")))??;

    // Check if the host process is running. If running, hot-reload its config;
    // if not running, spawn it from the plugin manifest so it connects to QQ immediately.
    let supervisor = state.supervisor();
    if supervisor.find_host_for_plugin(QQ_PLUGIN_ID).await.is_some() {
        if let Err(e) = supervisor.reload_plugin_config(QQ_PLUGIN_ID, &config).await {
            tracing::warn!(error = %e, "Failed to hot-reload QQ Official plugin config; attempting host restart");
            let host_id = format!("host_{}", QQ_PLUGIN_ID.replace('.', "_"));
            let _ = supervisor.restart_host(&host_id).await;
        }
    } else {
        let manifest_path = std::path::Path::new("./plugins/qqofficial/plugin.toml");
        if manifest_path.exists() {
            if let Err(err) = supervisor.spawn_from_manifest(manifest_path, None).await {
                tracing::error!(error = %err, "Failed to spawn QQ Official plugin host after QR bind");
            } else {
                tracing::info!("Spawned QQ Official plugin host successfully after QR bind");
            }
        }
    }

    Ok(())
}

