//! Central Pipeline Engine and asynchronous worker loop.
//!
//! Consumes inbound events from the CoreApiService MPSC queue, sequences them through
//! the PreFilter interception chain and CommandRouter, and emits outbound delivery requests.

use std::sync::Arc;
use tokio::sync::mpsc;
use tokio::task::JoinHandle;

use kanon_llm::tool_router::ToolRouter;
use kanon_proto::v1::message_segment::Segment;
use kanon_proto::v1::{
    DeliverMessageRequest, IngestEventRequest, MessageSegment, PipelineEventRequest,
};

use crate::pipeline::command::CommandRouter;
use crate::pipeline::pre_filter::{PreFilterChain, PreFilterOutcome};
use crate::supervisor::Supervisor;

/// Result produced after processing an event through the pipeline engine.
#[derive(Debug, Clone)]
pub enum PipelineResult {
    /// Inbound event was intercepted and blocked by a PreFilter plugin.
    Blocked {
        /// Identifier of the host that blocked the event.
        host_id: String,
        /// Outbound reply messages generated by the blocking pre-filter.
        replies: Vec<MessageSegment>,
    },
    /// A registered slash command was matched and executed by a plugin host.
    CommandExecuted {
        /// The slash command name executed (without leading slash).
        command: String,
        /// Target plugin identifier that handled the command.
        plugin_id: String,
        /// Identifier of the host process running the plugin.
        host_id: String,
        /// Execution status returned by the plugin host.
        success: bool,
        /// Outbound reply segments generated by the command handler.
        replies: Vec<MessageSegment>,
    },
    /// A slash command syntax was parsed, but no registered plugin matched the command name.
    CommandNotFound {
        /// Command name that failed to match.
        command: String,
    },
    /// Inbound conversational message was processed by LLM reasoning and generated a reply.
    LlmReplied {
        /// Natural language text generated by the model.
        content: String,
        /// Outbound reply segments generated for the conversational response.
        replies: Vec<MessageSegment>,
    },
    /// Inbound event passed through the pipeline without matching any slash command or LLM rule.
    Passed(PipelineEventRequest),
}

/// Central event processing engine driving the message pipeline.
pub struct PipelineEngine {
    /// Reference to the process supervisor managing active plugin hosts.
    supervisor: Arc<Supervisor>,
    /// Optional outbound channel for sending formatted replies to IM platform adapters.
    outbound_sender: Option<mpsc::Sender<DeliverMessageRequest>>,
    /// Optional ToolRouter driving LLM reasoning and cross-language tool calling.
    tool_router: Option<Arc<ToolRouter>>,
}

impl PipelineEngine {
    /// Creates a new `PipelineEngine` with the given supervisor and optional outbound message channel.
    pub fn new(
        supervisor: Arc<Supervisor>,
        outbound_sender: Option<mpsc::Sender<DeliverMessageRequest>>,
    ) -> Self {
        Self {
            supervisor,
            outbound_sender,
            tool_router: None,
        }
    }

    /// Attaches an LLM [`ToolRouter`] to enable multi-turn reasoning and tool calling.
    pub fn with_tool_router(mut self, tool_router: Arc<ToolRouter>) -> Self {
        self.tool_router = Some(tool_router);
        self
    }

    /// Processes a single inbound event through the PreFilter chain and command dispatcher.
    pub async fn process_event(&self, event: PipelineEventRequest) -> PipelineResult {
        let hosts = self.supervisor.get_all_hosts().await;

        // Phase 1: PreFilter Interception Chain
        let filtered_event = match PreFilterChain::execute(event, &hosts).await {
            PreFilterOutcome::Blocked {
                host_id,
                reply_messages,
            } => {
                tracing::info!(
                    host_id = %host_id,
                    "Event blocked by PreFilter chain; halting pipeline execution"
                );
                return PipelineResult::Blocked {
                    host_id,
                    replies: reply_messages,
                };
            }
            PreFilterOutcome::Passed(evt) => evt,
        };

        // Phase 2: Command Router matching
        // Extract raw text or inspect primary text segment if raw_text is empty.
        let text_candidate = if !filtered_event.raw_text.is_empty() {
            filtered_event.raw_text.clone()
        } else {
            filtered_event
                .segments
                .iter()
                .find_map(|s| match &s.segment {
                    Some(Segment::Text(t)) => Some(t.content.clone()),
                    _ => None,
                })
                .unwrap_or_default()
        };

        if let Some((cmd_name, args)) = CommandRouter::parse_command(&text_candidate) {
            if let Some(target) = CommandRouter::resolve(&cmd_name, &hosts) {
                tracing::debug!(
                    command = %cmd_name,
                    plugin_id = %target.plugin_id,
                    host_id = %target.host.host_id,
                    "Routing slash command to target host"
                );

                match CommandRouter::dispatch(&target, args, filtered_event.clone()).await {
                    Ok(response) => {
                        return PipelineResult::CommandExecuted {
                            command: cmd_name,
                            plugin_id: target.plugin_id,
                            host_id: target.host.host_id.clone(),
                            success: response.success,
                            replies: response.replies,
                        };
                    }
                    Err(status) => {
                        tracing::error!(
                            command = %cmd_name,
                            host_id = %target.host.host_id,
                            error = %status,
                            "Command execution failed with gRPC status"
                        );
                        return PipelineResult::CommandExecuted {
                            command: cmd_name,
                            plugin_id: target.plugin_id,
                            host_id: target.host.host_id.clone(),
                            success: false,
                            replies: vec![],
                        };
                    }
                }
            } else {
                tracing::debug!(
                    command = %cmd_name,
                    "Slash command detected but no matching plugin was registered"
                );
                return PipelineResult::CommandNotFound { command: cmd_name };
            }
        }

        // Phase 3: Conversational message (unmatched by command router, routed to LLM if enabled)
        if let Some(ref router) = self.tool_router
            && !text_candidate.is_empty()
        {
            let session_id = format!("{}:{}", filtered_event.channel_id, filtered_event.sender_id);
            match router.execute(&session_id, &text_candidate, &hosts).await {
                Ok(output) if !output.content.is_empty() => {
                    let reply = MessageSegment {
                        segment: Some(Segment::Text(kanon_proto::v1::TextSegment {
                            content: output.content.clone(),
                        })),
                    };
                    return PipelineResult::LlmReplied {
                        content: output.content,
                        replies: vec![reply],
                    };
                }
                Ok(_) => {
                    tracing::debug!("LLM returned empty completion; passing downstream");
                }
                Err(e) => {
                    tracing::error!(
                        session_id = %session_id,
                        error = %e,
                        "LLM reasoning and tool execution failed"
                    );
                }
            }
        }

        PipelineResult::Passed(filtered_event)
    }

    /// Runs the asynchronous worker loop, draining events from the ingest receiver.
    ///
    /// For every ingested event, the worker runs the pipeline and routes any outbound
    /// replies to the registered outbound message sender channel.
    pub async fn run_worker_loop(&self, mut event_receiver: mpsc::Receiver<IngestEventRequest>) {
        tracing::info!("Pipeline worker loop started");

        while let Some(req) = event_receiver.recv().await {
            let event = match req.event {
                Some(evt) => evt,
                None => {
                    tracing::warn!("Received IngestEventRequest with empty inner event; skipping");
                    continue;
                }
            };

            let platform = if !event.platform.is_empty() {
                event.platform.clone()
            } else {
                req.platform.clone()
            };
            let channel_id = event.channel_id.clone();
            let recipient_id = event.sender_id.clone();
            let event_id = event.event_id.clone();

            let result = self.process_event(event).await;

            if let Some(ref outbound_tx) = self.outbound_sender {
                let replies = match &result {
                    PipelineResult::Blocked { replies, .. } => replies,
                    PipelineResult::CommandExecuted { replies, .. } => replies,
                    PipelineResult::LlmReplied { replies, .. } => replies,
                    _ => &[][..],
                };

                if !replies.is_empty() {
                    let deliver_req = DeliverMessageRequest {
                        platform,
                        channel_id,
                        recipient_id,
                        segments: replies.to_vec(),
                    };

                    if let Err(e) = outbound_tx.send(deliver_req).await {
                        tracing::warn!(
                            event_id = %event_id,
                            error = %e,
                            "Failed to enqueue outbound message; receiver dropped"
                        );
                    }
                }
            }
        }

        tracing::info!("Pipeline worker loop terminated");
    }

    /// Spawns the pipeline worker loop as a background Tokio task.
    pub fn start_worker(
        self: Arc<Self>,
        event_receiver: mpsc::Receiver<IngestEventRequest>,
    ) -> JoinHandle<()> {
        tokio::spawn(async move {
            self.run_worker_loop(event_receiver).await;
        })
    }
}
