//! Central Pipeline Engine and asynchronous worker loop.
//!
//! Consumes inbound events from the CoreApiService MPSC queue, sequences them through
//! the PreFilter interception chain and CommandRouter, and dispatches outbound replies to the
//! platform adapter that owns the destination platform.
//!
//! # Why outbound is queued instead of awaited
//! Platform delivery performs network I/O against an external service. Awaiting it inside the
//! pipeline worker would let one slow platform stall every other conversation (head-of-line
//! blocking), so replies are handed to a bounded queue drained by an independent dispatcher task.
//! The queue is deliberately bounded: when a platform cannot keep up, the overflow is reported as
//! an explicit `OutboundFailed` stage instead of growing memory without limit.

use std::sync::Arc;
use tokio::sync::{Mutex, mpsc};
use tokio::task::JoinHandle;

use kanon_llm::tool_router::ToolRouter;
use kanon_proto::v1::message_segment::Segment;
use kanon_proto::v1::{
    DeliverMessageRequest, IngestEventRequest, MessageSegment, PipelineEventRequest,
};

use crate::adapter::{AdapterError, AdapterKind};
use crate::pipeline::command::CommandRouter;
use crate::pipeline::dead_letter::DeadLetterWriter;
use crate::pipeline::observer::{PipelineObserver, PipelineStage};
use crate::pipeline::pre_filter::{PreFilterChain, PreFilterOutcome};
use crate::supervisor::circuit_breaker::CircuitBreaker;
use crate::supervisor::{AdapterRoute, Supervisor};

/// Default depth of the outbound delivery queue.
///
/// Sized so that a slow platform absorbs a burst of replies without dropping any, while keeping
/// worst-case memory bounded.
pub const DEFAULT_OUTBOUND_QUEUE_CAPACITY: usize = 1024;

/// Default depth of the dedicated outbound delivery queue for each platform partition.
///
/// Preserves sequential FIFO delivery per platform while providing strict cross-platform
/// concurrency isolation so one slow platform never starves others.
pub const DEFAULT_PLATFORM_QUEUE_CAPACITY: usize = 64;

/// Result produced after processing an event through the pipeline engine.
#[derive(Debug, Clone)]
pub enum PipelineResult {
    /// Inbound event was intercepted and blocked by a PreFilter plugin.
    Blocked {
        /// Identifier of the host that blocked the event.
        host_id: String,
        /// Outbound reply messages generated by the blocking pre-filter.
        replies: Vec<MessageSegment>,
    },
    /// A registered slash command was matched and executed by a plugin host.
    CommandExecuted {
        /// The slash command name executed (without leading slash).
        command: String,
        /// Target plugin identifier that handled the command.
        plugin_id: String,
        /// Identifier of the host process running the plugin.
        host_id: String,
        /// Execution status returned by the plugin host.
        success: bool,
        /// Outbound reply segments generated by the command handler.
        replies: Vec<MessageSegment>,
    },
    /// A slash command syntax was parsed, but no registered plugin matched the command name.
    CommandNotFound {
        /// Command name that failed to match.
        command: String,
    },
    /// Inbound conversational message was processed by LLM reasoning and generated a reply.
    LlmReplied {
        /// Natural language text generated by the model.
        content: String,
        /// Outbound reply segments generated for the conversational response.
        replies: Vec<MessageSegment>,
    },
    /// Inbound event passed through the pipeline without matching any slash command or LLM rule.
    Passed(PipelineEventRequest),
}

/// Result produced after delivering an outbound message through a platform adapter.
#[derive(Debug, Clone)]
pub struct DeliveryOutcome {
    /// Which adapter route served the message.
    pub kind: AdapterKind,
    /// Platform that accepted the message.
    pub platform: String,
    /// Platform-assigned message identifier, when reported.
    pub message_id: String,
}

/// Central event processing engine driving the message pipeline.
pub struct PipelineEngine {
    /// Reference to the process supervisor managing active plugin hosts and adapters.
    supervisor: Arc<Supervisor>,
    /// Optional ToolRouter driving LLM reasoning and cross-language tool calling.
    tool_router: Option<Arc<ToolRouter>>,
    /// Optional lifecycle observer used by the management control plane for tracing.
    observer: Option<Arc<dyn PipelineObserver>>,
    /// Persistent dead-letter queue writer for failed or dropped outbound messages.
    dead_letter: Arc<DeadLetterWriter>,
    /// Producer side of the bounded outbound delivery queue.
    outbound_sender: mpsc::Sender<DeliverMessageRequest>,
    /// Consumer side, taken exactly once by [`PipelineEngine::start_outbound_dispatcher`].
    outbound_receiver: Mutex<Option<mpsc::Receiver<DeliverMessageRequest>>>,
}

impl PipelineEngine {
    /// Creates a new `PipelineEngine` bound to a supervisor.
    ///
    /// The outbound delivery queue is created here so producers always have a valid sender, even
    /// when the dispatcher task has not been started yet.
    pub fn new(supervisor: Arc<Supervisor>) -> Self {
        let (outbound_sender, outbound_receiver) = mpsc::channel(DEFAULT_OUTBOUND_QUEUE_CAPACITY);
        Self {
            supervisor,
            tool_router: None,
            observer: None,
            dead_letter: Arc::new(DeadLetterWriter::default()),
            outbound_sender,
            outbound_receiver: Mutex::new(Some(outbound_receiver)),
        }
    }

    /// Overrides the default dead letter writer.
    pub fn with_dead_letter(mut self, dead_letter: Arc<DeadLetterWriter>) -> Self {
        self.dead_letter = dead_letter;
        self
    }

    /// Returns a reference to the active dead letter writer.
    pub fn dead_letter(&self) -> &Arc<DeadLetterWriter> {
        &self.dead_letter
    }

    /// Attaches an LLM [`ToolRouter`] to enable multi-turn reasoning and tool calling.
    pub fn with_tool_router(mut self, tool_router: Arc<ToolRouter>) -> Self {
        self.tool_router = Some(tool_router);
        self
    }

    /// Attaches a lifecycle observer for control-plane tracing.
    pub fn with_observer(mut self, observer: Arc<dyn PipelineObserver>) -> Self {
        self.observer = Some(observer);
        self
    }

    /// Returns a handle for enqueuing outbound messages from outside the worker loop.
    pub fn outbound_sender(&self) -> mpsc::Sender<DeliverMessageRequest> {
        self.outbound_sender.clone()
    }

    /// Publishes a lifecycle stage to the attached observer, if any.
    ///
    /// Observation is deliberately infallible: tracing must never alter pipeline outcomes.
    fn observe(&self, stage: PipelineStage) {
        if let Some(ref observer) = self.observer {
            observer.on_stage(&stage);
        }
    }

    /// Delivers one outbound message to the adapter owning its platform.
    ///
    /// Routing order is built-in adapter first, then plugin host. Every failure path is explicit:
    /// an unrouted platform, an unreachable plugin host, or a plugin that reports `success=false`
    /// all become [`AdapterError`] values instead of a silent drop.
    pub async fn deliver_outbound(
        &self,
        request: DeliverMessageRequest,
    ) -> Result<DeliveryOutcome, AdapterError> {
        let platform = request.platform.clone();

        match self.supervisor.resolve_adapter(&platform).await {
            Some(AdapterRoute::Builtin(adapter)) => {
                let response = adapter.deliver(request).await?;
                if !response.success {
                    return Err(AdapterError::Delivery {
                        platform,
                        reason: response.error_message,
                    });
                }
                Ok(DeliveryOutcome {
                    kind: AdapterKind::Builtin,
                    platform,
                    message_id: response.message_id,
                })
            }
            Some(AdapterRoute::Plugin { host, plugin_id }) => {
                let host_id = host.host_id.clone();
                let response = host.deliver_message(request).await.map_err(|status| {
                    AdapterError::Delivery {
                        platform: platform.clone(),
                        reason: format!("plugin '{plugin_id}' on host '{host_id}' failed: {status}"),
                    }
                })?;

                if !response.success {
                    return Err(AdapterError::Delivery {
                        platform,
                        reason: format!(
                            "plugin '{plugin_id}' on host '{host_id}' rejected the message: {}",
                            response.error_message
                        ),
                    });
                }

                Ok(DeliveryOutcome {
                    kind: AdapterKind::Plugin,
                    platform,
                    message_id: response.message_id,
                })
            }
            None => Err(AdapterError::UnknownPlatform(platform)),
        }
    }

    /// Delivers a single outbound message and publishes the resulting observation stage,
    /// protected by the platform's adaptive circuit breaker and cold-storage dead-letter queue.
    pub async fn dispatch_outbound_request(&self, request: DeliverMessageRequest) {
        let breaker = self.supervisor.platform_circuit_breaker(&request.platform).await;
        self.dispatch_outbound_request_with_breaker(request, &breaker).await;
    }

    /// Delivers a single outbound message using the given platform circuit breaker.
    ///
    /// # Fault Tolerance & Dead-Letter Persistence
    /// - If the breaker is `Open`, fast-skips the call, publishes [`PipelineStage::OutboundFailed`],
    ///   and appends the dropped message to `data/dead_letter/<platform>_<date>.jsonl`.
    /// - If delivery succeeds, records latency in the breaker and publishes [`PipelineStage::OutboundDelivered`].
    /// - If delivery fails, increments consecutive failures in the breaker (tripping if threshold reached),
    ///   persists the message to the dead-letter log, and publishes [`PipelineStage::OutboundFailed`].
    pub async fn dispatch_outbound_request_with_breaker(
        &self,
        request: DeliverMessageRequest,
        breaker: &CircuitBreaker,
    ) {
        let platform = request.platform.clone();
        let channel_id = request.channel_id.clone();
        let segment_count = request.segments.len();

        if !breaker.allow_request() {
            let reason = "platform circuit breaker open".to_string();
            tracing::warn!(
                platform = %platform,
                channel_id = %channel_id,
                "Platform circuit breaker tripped (OPEN); short-circuiting delivery and persisting to dead letter"
            );
            if let Err(err) = self.dead_letter.write_record(&request, &reason).await {
                tracing::error!(
                    platform = %platform,
                    error = %err,
                    "Failed to record dead-letter entry for short-circuited message"
                );
            }
            self.observe(PipelineStage::OutboundFailed {
                platform,
                channel_id,
                reason: "circuit breaker open, persisted to dead letter".to_string(),
            });
            return;
        }

        let start = std::time::Instant::now();
        match self.deliver_outbound(request.clone()).await {
            Ok(outcome) => {
                breaker.record_success(start.elapsed());
                tracing::debug!(
                    platform = %outcome.platform,
                    channel_id = %channel_id,
                    message_id = %outcome.message_id,
                    "Outbound message delivered"
                );
                self.observe(PipelineStage::OutboundDelivered {
                    platform: outcome.platform,
                    channel_id,
                    segment_count,
                    target: outcome.kind,
                    message_id: outcome.message_id,
                });
            }
            Err(err) => {
                let reason = err.to_string();
                breaker.record_failure(&reason);
                tracing::warn!(
                    platform = %platform,
                    channel_id = %channel_id,
                    error = %err,
                    "Outbound delivery failed; persisting to dead letter"
                );
                if let Err(write_err) = self.dead_letter.write_record(&request, &reason).await {
                    tracing::error!(
                        platform = %platform,
                        error = %write_err,
                        "Failed to persist dead letter record"
                    );
                }
                self.observe(PipelineStage::OutboundFailed {
                    platform,
                    channel_id,
                    reason,
                });
            }
        }
    }

    /// Spawns a dedicated sequential worker task for a single platform partition.
    fn spawn_platform_worker(
        self: &Arc<Self>,
        platform: String,
        mut rx: mpsc::Receiver<DeliverMessageRequest>,
    ) {
        let engine = Arc::clone(self);
        tokio::spawn(async move {
            tracing::debug!(platform = %platform, "Platform outbound worker spawned");
            let breaker = engine.supervisor.platform_circuit_breaker(&platform).await;
            loop {
                // Workers retire after 30 seconds of inactivity to reclaim resources.
                match tokio::time::timeout(std::time::Duration::from_secs(30), rx.recv()).await {
                    Ok(Some(req)) => {
                        engine.dispatch_outbound_request_with_breaker(req, &breaker).await;
                    }
                    Ok(None) => {
                        // All channel senders dropped (shutting down).
                        break;
                    }
                    Err(_) => {
                        // Idle timeout reached; retire this worker.
                        tracing::debug!(platform = %platform, "Platform outbound worker idle timeout; retiring");
                        break;
                    }
                }
            }
        });
    }

    /// Reports an outbound drop when a specific platform's worker queue is saturated,
    /// and asynchronously flushes the dropped message to the dead-letter queue log.
    fn report_outbound_queue_full(&self, dropped: DeliverMessageRequest) {
        let platform = dropped.platform.clone();
        let channel_id = dropped.channel_id.clone();
        tracing::warn!(
            platform = %platform,
            channel_id = %channel_id,
            "Platform outbound queue saturated; dropping message to dead letter to prevent cross-platform backpressure"
        );
        let dead_letter = Arc::clone(&self.dead_letter);
        tokio::spawn(async move {
            let _ = dead_letter
                .write_record(&dropped, "platform outbound queue saturated")
                .await;
        });
        self.observe(PipelineStage::OutboundFailed {
            platform,
            channel_id,
            reason: "platform outbound queue full".to_string(),
        });
    }

    /// Drains the global outbound queue and partitions requests into per-platform sequential workers.
    ///
    /// # Concurrency & Ordering Guarantee
    /// - **Per-platform FIFO ordering**: Each platform has an independent sequential worker. Messages
    ///   for platform `A` are processed strictly in arrival order.
    /// - **Cross-platform isolation**: Platform `A` being slow, stalled, or failing never blocks
    ///   outbound deliveries to platform `B`.
    /// - **Bounded queue protection**: If platform `A`'s queue reaches capacity, overflow messages
    ///   are dropped and emit [`PipelineStage::OutboundFailed`], without stalling the global dispatcher.
    pub async fn run_outbound_loop(
        self: Arc<Self>,
        mut receiver: mpsc::Receiver<DeliverMessageRequest>,
    ) {
        tracing::info!("Partitioned outbound adapter dispatcher started");
        let mut workers: std::collections::HashMap<String, mpsc::Sender<DeliverMessageRequest>> =
            std::collections::HashMap::new();

        while let Some(request) = receiver.recv().await {
            let platform = request.platform.clone();

            // Periodic cleanup of dead channels to avoid memory buildup when platforms are dynamic
            if workers.len() > 128 {
                workers.retain(|_, tx| !tx.is_closed());
            }

            let tx = match workers.get(&platform) {
                Some(tx) if !tx.is_closed() => tx.clone(),
                _ => {
                    let (new_tx, rx) = mpsc::channel(DEFAULT_PLATFORM_QUEUE_CAPACITY);
                    self.spawn_platform_worker(platform.clone(), rx);
                    workers.insert(platform.clone(), new_tx.clone());
                    new_tx
                }
            };

            match tx.try_send(request) {
                Ok(()) => {}
                Err(mpsc::error::TrySendError::Closed(req)) => {
                    // The worker timed out immediately before the send; respawn and retry once
                    let (new_tx, rx) = mpsc::channel(DEFAULT_PLATFORM_QUEUE_CAPACITY);
                    self.spawn_platform_worker(platform.clone(), rx);
                    workers.insert(platform, new_tx.clone());
                    if let Err(mpsc::error::TrySendError::Full(dropped)) = new_tx.try_send(req) {
                        self.report_outbound_queue_full(dropped);
                    }
                }
                Err(mpsc::error::TrySendError::Full(dropped)) => {
                    self.report_outbound_queue_full(dropped);
                }
            }
        }

        // Dropping `workers` closes all platform channel senders, allowing active workers to drain
        // their remaining queues before terminating.
        drop(workers);
        tracing::info!("Partitioned outbound adapter dispatcher terminated");
    }

    /// Spawns the outbound dispatcher task.
    ///
    /// Returns `None` when the dispatcher was already started: the queue has exactly one consumer,
    /// so a second call cannot be honoured and must not silently steal messages.
    pub fn start_outbound_dispatcher(self: Arc<Self>) -> Option<JoinHandle<()>> {
        let receiver = self
            .outbound_receiver
            .try_lock()
            .ok()
            .and_then(|mut guard| guard.take());

        let receiver = match receiver {
            Some(receiver) => receiver,
            None => {
                tracing::error!("Outbound dispatcher already running; ignoring duplicate start");
                return None;
            }
        };

        Some(tokio::spawn(async move {
            self.run_outbound_loop(receiver).await;
        }))
    }

    /// Processes a single inbound event through the PreFilter chain and command dispatcher.
    pub async fn process_event(&self, event: PipelineEventRequest) -> PipelineResult {
        let event_id = event.event_id.clone();
        let hosts = self.supervisor.get_all_hosts().await;

        // Phase 1: PreFilter Interception Chain
        self.observe(PipelineStage::PreFilterStarted {
            event_id: event_id.clone(),
            host_count: hosts.len(),
        });
        let filtered_event = match PreFilterChain::execute_with_observer(
            event,
            &hosts,
            self.observer.as_ref(),
        )
        .await
        {
            PreFilterOutcome::Blocked {
                host_id,
                reply_messages,
            } => {
                tracing::info!(
                    host_id = %host_id,
                    "Event blocked by PreFilter chain; halting pipeline execution"
                );
                self.observe(PipelineStage::PreFilterBlocked {
                    event_id,
                    host_id: host_id.clone(),
                });
                return PipelineResult::Blocked {
                    host_id,
                    replies: reply_messages,
                };
            }
            PreFilterOutcome::Passed(evt) => evt,
        };
        self.observe(PipelineStage::PreFilterPassed {
            event_id: event_id.clone(),
        });

        // Phase 2: Command Router matching
        // Extract raw text or inspect primary text segment if raw_text is empty.
        let text_candidate = if !filtered_event.raw_text.is_empty() {
            filtered_event.raw_text.clone()
        } else {
            filtered_event
                .segments
                .iter()
                .find_map(|s| match &s.segment {
                    Some(Segment::Text(t)) => Some(t.content.clone()),
                    _ => None,
                })
                .unwrap_or_default()
        };

        if let Some((cmd_name, args)) = CommandRouter::parse_command(&text_candidate) {
            if let Some(target) = CommandRouter::resolve(&cmd_name, &hosts) {
                tracing::debug!(
                    command = %cmd_name,
                    plugin_id = %target.plugin_id,
                    host_id = %target.host.host_id,
                    "Routing slash command to target host"
                );

                self.observe(PipelineStage::CommandMatched {
                    event_id: event_id.clone(),
                    command: cmd_name.clone(),
                    plugin_id: target.plugin_id.clone(),
                    host_id: target.host.host_id.clone(),
                });

                match CommandRouter::dispatch(&target, args, filtered_event.clone()).await {
                    Ok(response) => {
                        return PipelineResult::CommandExecuted {
                            command: cmd_name,
                            plugin_id: target.plugin_id,
                            host_id: target.host.host_id.clone(),
                            success: response.success,
                            replies: response.replies,
                        };
                    }
                    Err(status) => {
                        tracing::error!(
                            command = %cmd_name,
                            host_id = %target.host.host_id,
                            error = %status,
                            "Command execution failed with gRPC status"
                        );
                        return PipelineResult::CommandExecuted {
                            command: cmd_name,
                            plugin_id: target.plugin_id,
                            host_id: target.host.host_id.clone(),
                            success: false,
                            replies: vec![],
                        };
                    }
                }
            } else {
                tracing::debug!(
                    command = %cmd_name,
                    "Slash command detected but no matching plugin was registered"
                );
                self.observe(PipelineStage::CommandNotFound {
                    event_id,
                    command: cmd_name.clone(),
                });
                return PipelineResult::CommandNotFound { command: cmd_name };
            }
        }

        // Phase 3: Conversational message (unmatched by command router, routed to LLM if enabled)
        if let Some(ref router) = self.tool_router
            && !text_candidate.is_empty()
        {
            let session_id = format!("{}:{}", filtered_event.channel_id, filtered_event.sender_id);
            // Filter hosts whose circuit breaker is Open to fast-skip them and protect LLM throughput
            let mut active_hosts = Vec::new();
            for host in &hosts {
                if host.circuit_breaker.allow_request() {
                    active_hosts.push(Arc::clone(host));
                } else {
                    tracing::warn!(
                        host_id = %host.host_id,
                        event_id = %filtered_event.event_id,
                        "Circuit breaker is OPEN; fast-skipping host from ToolRouter candidates"
                    );
                    self.observe(PipelineStage::CircuitBreakerTripped {
                        event_id: filtered_event.event_id.clone(),
                        host_id: host.host_id.clone(),
                        phase: "tool_router".to_string(),
                        reason: format!(
                            "Circuit breaker OPEN (state: {:?}, consecutive failures: {})",
                            host.circuit_breaker.state(),
                            host.circuit_breaker.consecutive_failures()
                        ),
                    });
                }
            }

            match router.execute(&session_id, &text_candidate, &active_hosts).await {
                Ok(output) if !output.content.is_empty() => {
                    let reply = MessageSegment {
                        segment: Some(Segment::Text(kanon_proto::v1::TextSegment {
                            content: output.content.clone(),
                        })),
                    };
                    self.observe(PipelineStage::LlmReplied {
                        event_id,
                        session_id,
                        content_length: output.content.chars().count(),
                    });
                    return PipelineResult::LlmReplied {
                        content: output.content,
                        replies: vec![reply],
                    };
                }
                Ok(_) => {
                    tracing::debug!("LLM returned empty completion; passing downstream");
                }
                Err(e) => {
                    tracing::error!(
                        session_id = %session_id,
                        error = %e,
                        "LLM reasoning and tool execution failed"
                    );
                }
            }
        }

        PipelineResult::Passed(filtered_event)
    }

    /// Runs the asynchronous worker loop, draining events from the ingest receiver.
    ///
    /// For every ingested event, the worker runs the pipeline and routes any outbound
    /// replies to the registered outbound message sender channel.
    pub async fn run_worker_loop(&self, mut event_receiver: mpsc::Receiver<IngestEventRequest>) {
        tracing::info!("Pipeline worker loop started");

        while let Some(req) = event_receiver.recv().await {
            let event = match req.event {
                Some(evt) => evt,
                None => {
                    tracing::warn!("Received IngestEventRequest with empty inner event; skipping");
                    continue;
                }
            };

            let platform = if !event.platform.is_empty() {
                event.platform.clone()
            } else {
                req.platform.clone()
            };
            let channel_id = event.channel_id.clone();
            let recipient_id = event.sender_id.clone();
            let event_id = event.event_id.clone();

            self.observe(PipelineStage::Ingested {
                event_id: event_id.clone(),
                platform: platform.clone(),
                channel_id: channel_id.clone(),
                sender_id: recipient_id.clone(),
            });

            let result = self.process_event(event).await;

            let replies = match &result {
                PipelineResult::Blocked { replies, .. } => replies,
                PipelineResult::CommandExecuted { replies, .. } => replies,
                PipelineResult::LlmReplied { replies, .. } => replies,
                _ => &[][..],
            };

            if !replies.is_empty() {
                let deliver_req = DeliverMessageRequest {
                    platform,
                    channel_id,
                    recipient_id,
                    segments: replies.to_vec(),
                    event_id: event_id.clone(),
                };

                let platform = deliver_req.platform.clone();
                let channel_id = deliver_req.channel_id.clone();
                let segment_count = deliver_req.segments.len();

                // Non-blocking hand-off: the pipeline worker must never await platform I/O.
                match self.outbound_sender.try_send(deliver_req) {
                    Ok(()) => {
                        self.observe(PipelineStage::OutboundQueued {
                            event_id,
                            platform,
                            channel_id,
                            segment_count,
                        });
                    }
                    Err(mpsc::error::TrySendError::Full(dropped)) => {
                        tracing::warn!(
                            platform = %platform,
                            channel_id = %channel_id,
                            "Outbound queue is full; dropping reply to dead letter to protect pipeline latency"
                        );
                        let dead_letter = Arc::clone(&self.dead_letter);
                        tokio::spawn(async move {
                            let _ = dead_letter.write_record(&dropped, "outbound queue is full").await;
                        });
                        self.observe(PipelineStage::OutboundFailed {
                            platform,
                            channel_id,
                            reason: "outbound queue is full; reply dropped".to_string(),
                        });
                    }
                    Err(mpsc::error::TrySendError::Closed(_)) => {
                        tracing::warn!(
                            platform = %platform,
                            channel_id = %channel_id,
                            "Outbound dispatcher is not running; dropping reply"
                        );
                        self.observe(PipelineStage::OutboundFailed {
                            platform,
                            channel_id,
                            reason: "outbound dispatcher is not running; reply dropped".to_string(),
                        });
                    }
                }
            }
        }

        tracing::info!("Pipeline worker loop terminated");
    }

    /// Spawns the pipeline worker loop as a background Tokio task.
    pub fn start_worker(
        self: Arc<Self>,
        event_receiver: mpsc::Receiver<IngestEventRequest>,
    ) -> JoinHandle<()> {
        tokio::spawn(async move {
            self.run_worker_loop(event_receiver).await;
        })
    }
}
