//! Domain types for LLM requests, responses, messages, and tools.
//!
//! These unified domain types decouple the internal Kanon engine from provider-specific
//! wire formats (e.g. OpenAI JSON vs Ollama JSON).

use serde::{Deserialize, Serialize};

/// Role assumed by a conversational message participant.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// Persona instructions or operational parameters for the model.
    System,
    /// Message sent by the end-user.
    User,
    /// Response or reasoning output generated by the model.
    Assistant,
    /// Execution output returned by a plugin tool.
    Tool,
}

/// A conversational message within an LLM interaction.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChatMessage {
    /// Message sender role.
    pub role: Role,

    /// Textual content of the message. Optional when assistant invokes tools.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// Tool call requests generated by the model (present when role == Assistant).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,

    /// Identifier matching the `ToolCall.id` when responding with tool execution output (role == Tool).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,

    /// Optional participant or function name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ChatMessage {
    /// Creates a system persona message.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: Role::System,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
            name: None,
        }
    }

    /// Creates a user input message.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
            name: None,
        }
    }

    /// Creates an assistant text response message.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: Role::Assistant,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
            name: None,
        }
    }

    /// Creates an assistant message containing one or more tool calls.
    pub fn assistant_tool_calls(tool_calls: Vec<ToolCall>, content: Option<String>) -> Self {
        Self {
            role: Role::Assistant,
            content,
            tool_calls: Some(tool_calls),
            tool_call_id: None,
            name: None,
        }
    }

    /// Creates a tool response message providing execution results back to the model.
    pub fn tool_response(tool_call_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: Role::Tool,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: Some(tool_call_id.into()),
            name: None,
        }
    }
}

/// Normalized description of a tool presented to the model for function calling.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolDefinition {
    /// Unique identifier / function name of the tool.
    pub name: String,
    /// Natural language explanation of what the tool accomplishes.
    pub description: String,
    /// JSON Schema object describing the arguments accepted by the tool.
    pub parameters: serde_json::Value,
}

/// An individual tool call emitted by the model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolCall {
    /// Provider-allocated unique call identifier (e.g. `call_abc123`).
    pub id: String,
    /// Target tool name to execute.
    pub name: String,
    /// Structured argument dictionary parsed into a JSON value.
    pub arguments: serde_json::Value,
}

/// Request payload sent to an LLM provider client.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatRequest {
    /// Model identifier to invoke (e.g. `deepseek-chat`, `gpt-4o-mini`, `llama3`).
    pub model: String,
    /// Complete conversational message sequence including history and instructions.
    pub messages: Vec<ChatMessage>,
    /// Tool definitions available for the model to invoke.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub tools: Vec<ToolDefinition>,
    /// Sampling temperature (0.0 to 2.0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,
    /// Maximum tokens allowed in the generated output.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
}

/// Token utilization statistics returned by the provider.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Tokens consumed by input prompt and history.
    pub prompt_tokens: u32,
    /// Tokens consumed by model generation.
    pub completion_tokens: u32,
    /// Total tokens billed or consumed.
    pub total_tokens: u32,
}

/// Normalized completion response returned from an LLM provider.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ChatResponse {
    /// Generated text content, if any.
    pub content: Option<String>,
    /// List of tool calls requested by the model.
    pub tool_calls: Vec<ToolCall>,
    /// Termination reason (e.g. `stop`, `tool_calls`, `length`).
    pub finish_reason: Option<String>,
    /// Token usage metrics for this inference step.
    pub usage: Option<TokenUsage>,
}

/// A streaming chunk emitted during model generation.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ChatChunk {
    /// Incremental textual delta generated in this chunk.
    pub delta_text: String,
    /// Incremental reasoning or thinking delta (e.g. DeepSeek Reasoner, OpenAI o1/o3).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_text: Option<String>,
    /// Whether this chunk marks the completion of the generation stream.
    pub is_finished: bool,
    /// Termination reason, present on final chunk (e.g. `stop`, `tool_calls`, `length`).
    pub finish_reason: Option<String>,
    /// Incremental or assembled tool calls, if any.
    pub tool_calls: Vec<ToolCall>,
}

impl ChatChunk {
    /// Creates a content text delta chunk.
    pub fn delta(text: impl Into<String>) -> Self {
        Self {
            delta_text: text.into(),
            reasoning_text: None,
            is_finished: false,
            finish_reason: None,
            tool_calls: Vec::new(),
        }
    }

    /// Creates a reasoning text delta chunk.
    pub fn reasoning(text: impl Into<String>) -> Self {
        Self {
            delta_text: String::new(),
            reasoning_text: Some(text.into()),
            is_finished: false,
            finish_reason: None,
            tool_calls: Vec::new(),
        }
    }

    /// Creates a completion chunk signaling stream termination.
    pub fn done(finish_reason: Option<String>) -> Self {
        Self {
            delta_text: String::new(),
            reasoning_text: None,
            is_finished: true,
            finish_reason,
            tool_calls: Vec::new(),
        }
    }
}

