//! Kanon Built-in Agent Engine.
//!
//! Provides a versatile, high-performance agent runtime suitable for both
//! conversational chat bots and autonomous goal-driven task agents.
//!
//! Fully modularized:
//! - Pluggable model providers implementing [`LlmProvider`];
//! - Pluggable conversational memory implementing [`Memory`];
//! - Native in-process tools implementing [`AgentTool`] (zero IPC overhead);
//! - Dynamic cross-process tool calling via [`ToolHost`];
//! - Extensible lifecycle hooks via [`AgentHook`] for RAG, guardrails, and tracing;
//! - Standalone execution mode via [`Agent::run_standalone`].

use async_trait::async_trait;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use kanon_proto::v1::{ToolCallRequest, tool_call_request, tool_call_response};

use crate::error::AgentError;
use crate::gateway::types::{
    ChatMessage, ChatRequest, ChatResponse, Role, ToolCall, ToolDefinition,
};
use crate::gateway::{ChatChunk, ChatChunkStream, LlmProvider};
use crate::memory::{Memory, SlidingWindowMemory};
use crate::tool_router::{
    ExecutedToolCall, ToolAttachment, ToolHost, aggregate_tools, json_to_prost_struct,
    prost_struct_to_json,
};
use tokio_stream::StreamExt;

/// Configuration parameters for agent reasoning and execution.
#[derive(Debug, Clone)]
pub struct AgentConfig {
    /// Maximum tool reasoning loop iterations before forcing termination.
    pub max_iterations: usize,
    /// Default model identifier.
    pub default_model: String,
    /// Optional sampling temperature.
    pub temperature: Option<f32>,
    /// Optional max tokens limit for completions.
    pub max_tokens: Option<u32>,
    /// Whether to halt immediately if a tool call returns an error.
    pub stop_on_tool_failure: bool,
}

impl Default for AgentConfig {
    fn default() -> Self {
        Self {
            max_iterations: 5,
            default_model: "gpt-4o-mini".to_string(),
            temperature: None,
            max_tokens: None,
            stop_on_tool_failure: false,
        }
    }
}

/// Result produced after an agent run concludes.
#[derive(Debug, Clone, PartialEq)]
pub struct AgentOutput {
    /// Final natural language response generated by the agent.
    pub content: String,
    /// Sequence of tool calls executed during the reasoning loop.
    pub executed_tools: Vec<ExecutedToolCall>,
    /// Total conversational / reasoning turns executed.
    pub turns: usize,
    /// Model-reported finish reason (e.g. `stop`, `tool_calls`, `length`).
    pub finish_reason: Option<String>,
    /// Rich media produced by the executed tool calls, deduplicated in execution order.
    ///
    /// The pipeline turns these into image/file segments on the outbound message, which is how a
    /// drawing tool's output reaches the chat platform instead of only its text description.
    pub attachments: Vec<ToolAttachment>,
}

/// Pluggable tool abstraction for in-process or native agent tools.
///
/// Allows developers, internal modules, or dynamic scripts to expose functions
/// directly to the agent without requiring external gRPC IPC processes.
#[async_trait]
pub trait AgentTool: Send + Sync {
    /// Name, description, and JSON schema describing parameter expectations.
    fn definition(&self) -> ToolDefinition;

    /// Invokes the tool implementation in-process.
    async fn call(&self, session_id: &str, arguments: serde_json::Value) -> Result<String, String>;
}

/// Helper type for asynchronous native tool closures.
pub type NativeToolFn = Arc<
    dyn Fn(&str, serde_json::Value) -> Pin<Box<dyn Future<Output = Result<String, String>> + Send>>
        + Send
        + Sync,
>;

/// In-process tool constructed directly from a definition and an async closure.
pub struct NativeTool {
    definition: ToolDefinition,
    handler: NativeToolFn,
}

impl NativeTool {
    /// Creates a new native in-process tool from a definition and an async handler.
    pub fn new<F, Fut>(definition: ToolDefinition, f: F) -> Self
    where
        F: Fn(&str, serde_json::Value) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = Result<String, String>> + Send + 'static,
    {
        Self {
            definition,
            handler: Arc::new(move |sid, args| Box::pin(f(sid, args))),
        }
    }
}

#[async_trait]
impl AgentTool for NativeTool {
    fn definition(&self) -> ToolDefinition {
        self.definition.clone()
    }

    async fn call(&self, session_id: &str, arguments: serde_json::Value) -> Result<String, String> {
        (self.handler)(session_id, arguments).await
    }
}

/// Lifecycle interception hooks for agent reasoning and execution.
///
/// Enables plugins and middleware to implement:
/// - RAG / semantic context retrieval injection before calling the LLM;
/// - Guardrails, safety verification, and permission confirmation before tool execution;
/// - Observability, tracing, token budget tracking, and latency auditing.
#[async_trait]
pub trait AgentHook: Send + Sync {
    /// Invoked immediately before transmitting the request payload to the model provider.
    async fn on_llm_request(
        &self,
        _session_id: &str,
        _request: &mut ChatRequest,
    ) -> Result<(), AgentError> {
        Ok(())
    }

    /// Invoked immediately upon receiving a completion response from the model.
    async fn on_llm_response(
        &self,
        _session_id: &str,
        _response: &mut ChatResponse,
    ) -> Result<(), AgentError> {
        Ok(())
    }

    /// Invoked before dispatching a tool execution.
    ///
    /// Return `Ok(true)` to permit execution, or `Ok(false)` to veto / reject execution.
    async fn on_before_tool_call(
        &self,
        _session_id: &str,
        _call: &ToolCall,
    ) -> Result<bool, AgentError> {
        Ok(true)
    }

    /// Invoked immediately following completion of a tool execution.
    async fn on_after_tool_call(
        &self,
        _session_id: &str,
        _call: &ToolCall,
        _result: &str,
        _success: bool,
    ) -> Result<(), AgentError> {
        Ok(())
    }
}

/// Fallback host used for standalone agent executions without external gRPC plugin processes.
#[derive(Debug, Clone, Default)]
pub struct NoopHost;

#[async_trait]
#[async_trait::async_trait]
impl ToolHost for NoopHost {
    fn host_id(&self) -> &str {
        "noop"
    }

    fn plugin_metas(&self) -> Vec<kanon_proto::v1::PluginMeta> {
        Vec::new()
    }

    async fn call_tool(
        &self,
        _req: ToolCallRequest,
    ) -> Result<kanon_proto::v1::ToolCallResponse, tonic::Status> {
        Err(tonic::Status::not_found(
            "No external plugin host available",
        ))
    }
}

/// General-purpose Kanon Agent.
///
/// Encapsulates model backend, memory store, native tools, lifecycle hooks, and reasoning policies.
pub struct Agent {
    /// Identifier or role name of this agent.
    name: String,
    /// Static or base system prompt setting the agent's persona and instructions.
    system_prompt: Option<String>,
    /// Provider backend for LLM completions.
    provider: Arc<dyn LlmProvider>,
    /// Pluggable memory backend for conversational history.
    memory: Arc<dyn Memory>,
    /// Optional session manager tracking lifecycle, turns, and metadata.
    session_manager: Option<Arc<crate::session::SessionManager>>,
    /// Optional persona registry for dynamic persona resolution.
    persona_registry: Option<Arc<crate::prompt::PersonaRegistry>>,
    /// Native in-process tools directly callable without IPC overhead.
    tools: Vec<Arc<dyn AgentTool>>,
    /// Lifecycle interception hooks.
    hooks: Vec<Arc<dyn AgentHook>>,
    /// Operational configuration.
    config: AgentConfig,
}

impl Agent {
    /// Returns a new fluent builder for constructing an [`Agent`].
    pub fn builder(name: impl Into<String>, provider: Arc<dyn LlmProvider>) -> AgentBuilder {
        AgentBuilder::new(name, provider)
    }

    /// Agent identifier name.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Reference to the active memory backend.
    pub fn memory(&self) -> &Arc<dyn Memory> {
        &self.memory
    }

    /// Reference to the optional session manager.
    pub fn session_manager(&self) -> Option<&Arc<crate::session::SessionManager>> {
        self.session_manager.as_ref()
    }

    /// Reference to the optional persona registry.
    pub fn persona_registry(&self) -> Option<&Arc<crate::prompt::PersonaRegistry>> {
        self.persona_registry.as_ref()
    }

    /// Reference to the underlying provider.
    pub fn provider(&self) -> &Arc<dyn LlmProvider> {
        &self.provider
    }

    /// Active agent configuration.
    pub fn config(&self) -> &AgentConfig {
        &self.config
    }

    /// Registered native tools.
    pub fn tools(&self) -> &[Arc<dyn AgentTool>] {
        &self.tools
    }

    /// Registered lifecycle hooks.
    pub fn hooks(&self) -> &[Arc<dyn AgentHook>] {
        &self.hooks
    }

    /// Executes the agent reasoning loop for an inbound message in standalone mode,
    /// using only native registered tools (or pure conversation) without requiring gRPC hosts.
    pub async fn run_standalone(
        &self,
        session_id: &str,
        user_input: &str,
    ) -> Result<AgentOutput, AgentError> {
        self.run(session_id, user_input, &[]).await
    }

    /// Executes the agent reasoning loop for an inbound message.
    ///
    /// # Flow:
    /// 1. Initializes session system prompt if not yet set in memory;
    /// 2. Records inbound user message in memory;
    /// 3. Dynamically queries active tools from native registered tools and plugin hosts;
    /// 4. Executes reasoning loop until model emits final text or iteration ceiling is hit;
    /// 5. Invokes lifecycle hooks around LLM requests, tool authorizations, and completions;
    /// 6. Dispatches tool calls (in-process for native tools, gRPC IPC for plugin tools);
    /// 7. Stores assistant reply in memory and returns [`AgentOutput`].
    pub async fn run(
        &self,
        session_id: &str,
        user_input: &str,
        hosts: &[Arc<dyn ToolHost>],
    ) -> Result<AgentOutput, AgentError> {
        // 1. Ensure system prompt is established for this session if configured
        if let Some(ref prompt) = self.system_prompt
            && self.memory.get_system_prompt(session_id).await?.is_none()
        {
            self.memory
                .set_system_prompt(session_id, prompt.clone())
                .await?;
        }

        // 2. Push user message to memory
        self.memory
            .push_message(session_id, ChatMessage::user(user_input))
            .await?;

        // 3. Dynamically aggregate tools from both native tools and active plugin hosts
        let mut tools = Vec::with_capacity(self.tools.len());
        for t in &self.tools {
            tools.push(t.definition());
        }
        tools.extend(aggregate_tools(hosts));

        let mut executed_tools = Vec::new();
        let mut attachments: Vec<ToolAttachment> = Vec::new();
        let mut iterations = 0;

        // 4. Reasoning and tool execution loop
        loop {
            let messages = self.memory.get_messages(session_id).await?;

            let mut request = ChatRequest {
                model: self.config.default_model.clone(),
                messages,
                tools: tools.clone(),
                temperature: self.config.temperature,
                max_tokens: self.config.max_tokens,
            };

            // Lifecycle Hook: before LLM request (e.g. for RAG / context enrichment)
            for hook in &self.hooks {
                hook.on_llm_request(session_id, &mut request).await?;
            }

            let mut response = self.provider.chat(&request).await?;

            // Lifecycle Hook: after LLM response (e.g. for auditing / token counting)
            for hook in &self.hooks {
                hook.on_llm_response(session_id, &mut response).await?;
            }

            // Terminal state: Model completed generation without requesting tools
            if response.tool_calls.is_empty() {
                let final_content = response.content.unwrap_or_default();
                if !final_content.is_empty() {
                    self.memory
                        .push_message(session_id, ChatMessage::assistant(&final_content))
                        .await?;
                }

                if let Some(ref sm) = self.session_manager {
                    let tokens_used = response
                        .usage
                        .as_ref()
                        .map(|u| u.total_tokens as usize)
                        .unwrap_or_else(|| {
                            crate::token::estimate_text_tokens(user_input)
                                + crate::token::estimate_text_tokens(&final_content)
                        });
                    sm.record_turn(session_id, tokens_used);
                }

                return Ok(AgentOutput {
                    content: final_content,
                    executed_tools,
                    turns: iterations + 1,
                    finish_reason: response.finish_reason,
                    attachments,
                });
            }

            // Guard against runaway loop recursion
            if iterations >= self.config.max_iterations {
                tracing::warn!(
                    agent = %self.name,
                    session_id = %session_id,
                    iterations = iterations,
                    "Agent reasoning iteration ceiling reached; breaking loop"
                );
                let fallback = response.content.unwrap_or_else(|| {
                    "Agent reasoning recursion limit reached; execution terminated.".to_string()
                });
                self.memory
                    .push_message(session_id, ChatMessage::assistant(&fallback))
                    .await?;

                if let Some(ref sm) = self.session_manager {
                    let tokens_used = crate::token::estimate_text_tokens(user_input)
                        + crate::token::estimate_text_tokens(&fallback);
                    sm.record_turn(session_id, tokens_used);
                }

                return Ok(AgentOutput {
                    content: fallback,
                    executed_tools,
                    turns: iterations + 1,
                    finish_reason: Some("max_iterations".to_string()),
                    attachments,
                });
            }

            iterations += 1;

            // Record assistant tool calls turn into history
            self.memory
                .push_message(
                    session_id,
                    ChatMessage {
                        role: Role::Assistant,
                        content: response.content.clone(),
                        tool_calls: Some(response.tool_calls.clone()),
                        tool_call_id: None,
                        name: None,
                    },
                )
                .await?;

            // Execute each requested tool call
            for call in response.tool_calls {
                // Hook: tool call permission / safety check
                let mut permitted = true;
                for hook in &self.hooks {
                    if !hook.on_before_tool_call(session_id, &call).await? {
                        permitted = false;
                        break;
                    }
                }
                if !permitted {
                    tracing::info!(agent = %self.name, tool = %call.name, "Tool call was vetoed by agent hook");
                    let veto_msg =
                        format!("Tool '{}' execution was denied by agent policy", call.name);
                    self.memory
                        .push_message(session_id, ChatMessage::tool_response(&call.id, &veto_msg))
                        .await?;
                    executed_tools.push(ExecutedToolCall {
                        call_id: call.id,
                        tool_name: call.name.clone(),
                        plugin_id: "policy".to_string(),
                        host_id: "agent_hook".to_string(),
                        success: false,
                    });
                    continue;
                }

                // Branch A: Check registered native in-process tools
                if let Some(native_tool) =
                    self.tools.iter().find(|t| t.definition().name == call.name)
                {
                    tracing::debug!(agent = %self.name, tool = %call.name, "Executing native tool in-process");
                    let (result_str, is_success) =
                        match native_tool.call(session_id, call.arguments.clone()).await {
                            Ok(res) => (res, true),
                            Err(err) => (format!("Error: {err}"), false),
                        };

                    executed_tools.push(ExecutedToolCall {
                        call_id: call.id.clone(),
                        tool_name: call.name.clone(),
                        plugin_id: "native".to_string(),
                        host_id: "in_process".to_string(),
                        success: is_success,
                    });

                    for hook in &self.hooks {
                        hook.on_after_tool_call(session_id, &call, &result_str, is_success)
                            .await?;
                    }

                    self.memory
                        .push_message(
                            session_id,
                            ChatMessage::tool_response(&call.id, &result_str),
                        )
                        .await?;

                    if !is_success && self.config.stop_on_tool_failure {
                        return Err(AgentError::Memory(format!(
                            "Native tool '{}' failed: {result_str}",
                            call.name
                        )));
                    }
                    continue;
                }

                // Branch B: Resolve tool on external gRPC plugin hosts
                let target = find_tool_target(&call.name, hosts);

                let (target_host, plugin_id, actual_tool_name) = match target {
                    Some((h, pid, tname)) => (h, pid, tname),
                    None => {
                        tracing::warn!(tool = %call.name, "Requested tool not declared by any native tool or active host");
                        let err_msg = format!("Tool '{}' not registered", call.name);
                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, &err_msg),
                            )
                            .await?;
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id,
                            tool_name: call.name.clone(),
                            plugin_id: "unknown".to_string(),
                            host_id: "unknown".to_string(),
                            success: false,
                        });
                        if self.config.stop_on_tool_failure {
                            return Err(AgentError::ToolNotFound(call.name));
                        }
                        continue;
                    }
                };

                // Zero-copy in-memory translation from serde_json::Value to prost_types::Struct
                let structured_args = match &call.arguments {
                    serde_json::Value::Object(_) => json_to_prost_struct(&call.arguments),
                    _ => None,
                };

                let tool_req = ToolCallRequest {
                    call_id: call.id.clone(),
                    tool_name: actual_tool_name,
                    session_id: session_id.to_string(),
                    payload: structured_args.map(tool_call_request::Payload::StructuredArgs),
                };

                tracing::debug!(
                    agent = %self.name,
                    tool = %call.name,
                    host_id = %target_host.host_id(),
                    plugin_id = %plugin_id,
                    "Agent dispatching tool RPC to host"
                );

                match target_host.call_tool(tool_req).await {
                    Ok(resp) => {
                        let is_success = resp.success;
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id.clone(),
                            tool_name: call.name.clone(),
                            plugin_id: plugin_id.clone(),
                            host_id: target_host.host_id().to_string(),
                            success: is_success,
                        });

                        // Attachments of a failed call are discarded with it: a partial image from
                        // an errored tool would be sent to the user as if it were a result.
                        if is_success {
                            for attachment in resp.attachments {
                                let attachment = ToolAttachment::from_proto(attachment);
                                if !attachments.contains(&attachment) {
                                    attachments.push(attachment);
                                }
                            }
                        }

                        let result_str = if !is_success {
                            format!("Error: {}", resp.error_message)
                        } else {
                            match resp.payload {
                                Some(tool_call_response::Payload::StructuredResult(s)) => {
                                    prost_struct_to_json(s).to_string()
                                }
                                Some(tool_call_response::Payload::RawBytes(bytes)) => {
                                    String::from_utf8_lossy(&bytes).to_string()
                                }
                                None => "{}".to_string(),
                            }
                        };

                        for hook in &self.hooks {
                            hook.on_after_tool_call(session_id, &call, &result_str, is_success)
                                .await?;
                        }

                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, result_str),
                            )
                            .await?;

                        if !is_success && self.config.stop_on_tool_failure {
                            tracing::warn!(tool = %call.name, "Tool reported failure and stop_on_tool_failure is enabled");
                            break;
                        }
                    }
                    Err(status) => {
                        tracing::error!(tool = %call.name, error = %status, "Tool RPC execution failed");
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id.clone(),
                            tool_name: call.name.clone(),
                            plugin_id: plugin_id.clone(),
                            host_id: target_host.host_id().to_string(),
                            success: false,
                        });

                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(
                                    &call.id,
                                    format!("RPC Error: {}", status.message()),
                                ),
                            )
                            .await?;

                        if self.config.stop_on_tool_failure {
                            return Err(AgentError::from(status));
                        }
                    }
                }
            }
        }
    }

    /// Executes the agent reasoning loop in standalone streaming mode, returning incremental chunks
    /// for the assistant's final response.
    ///
    /// If tool execution turns are required, they are executed internally before streaming
    /// the final text response. Upon stream completion, the full assistant message is
    /// committed into session memory.
    pub async fn run_standalone_stream(
        &self,
        session_id: &str,
        user_input: &str,
    ) -> Result<ChatChunkStream, AgentError> {
        self.run_stream(session_id, user_input, &[]).await
    }

    /// Executes the agent reasoning loop with tool resolution, streaming the final assistant response.
    pub async fn run_stream(
        &self,
        session_id: &str,
        user_input: &str,
        hosts: &[Arc<dyn ToolHost>],
    ) -> Result<ChatChunkStream, AgentError> {
        // 1. Ensure system prompt is established
        if let Some(ref prompt) = self.system_prompt
            && self.memory.get_system_prompt(session_id).await?.is_none()
        {
            self.memory
                .set_system_prompt(session_id, prompt.clone())
                .await?;
        }

        // 2. Push user message to memory
        self.memory
            .push_message(session_id, ChatMessage::user(user_input))
            .await?;

        // 3. Dynamically aggregate tools
        let mut tools = Vec::with_capacity(self.tools.len());
        for t in &self.tools {
            tools.push(t.definition());
        }
        tools.extend(aggregate_tools(hosts));

        let mut iterations = 0;

        // If tools are available, execute intermediate tool turns first
        while !tools.is_empty() && iterations < self.config.max_iterations {
            let messages = self.memory.get_messages(session_id).await?;
            let mut request = ChatRequest {
                model: self.config.default_model.clone(),
                messages,
                tools: tools.clone(),
                temperature: self.config.temperature,
                max_tokens: self.config.max_tokens,
            };

            for hook in &self.hooks {
                hook.on_llm_request(session_id, &mut request).await?;
            }

            let mut response = self.provider.chat(&request).await?;

            for hook in &self.hooks {
                hook.on_llm_response(session_id, &mut response).await?;
            }

            // If no tools were called, this is the final response
            if response.tool_calls.is_empty() {
                let final_content = response.content.unwrap_or_default();
                if !final_content.is_empty() {
                    self.memory
                        .push_message(session_id, ChatMessage::assistant(&final_content))
                        .await?;
                }
                let (tx, rx) = tokio::sync::mpsc::channel(2);
                let _ = tx.send(Ok(ChatChunk::delta(&final_content))).await;
                let _ = tx.send(Ok(ChatChunk::done(response.finish_reason))).await;
                return Ok(Box::pin(tokio_stream::wrappers::ReceiverStream::new(rx)));
            }

            // Otherwise, execute tools
            iterations += 1;
            self.memory
                .push_message(
                    session_id,
                    ChatMessage {
                        role: Role::Assistant,
                        content: response.content.clone(),
                        tool_calls: Some(response.tool_calls.clone()),
                        tool_call_id: None,
                        name: None,
                    },
                )
                .await?;

            for call in response.tool_calls {
                let mut permitted = true;
                for hook in &self.hooks {
                    if !hook.on_before_tool_call(session_id, &call).await? {
                        permitted = false;
                        break;
                    }
                }
                if !permitted {
                    let veto_msg =
                        format!("Tool '{}' execution was denied by agent policy", call.name);
                    self.memory
                        .push_message(session_id, ChatMessage::tool_response(&call.id, &veto_msg))
                        .await?;
                    continue;
                }

                if let Some(native_tool) =
                    self.tools.iter().find(|t| t.definition().name == call.name)
                {
                    let (result_str, is_success) =
                        match native_tool.call(session_id, call.arguments.clone()).await {
                            Ok(res) => (res, true),
                            Err(err) => (format!("Error: {err}"), false),
                        };
                    for hook in &self.hooks {
                        hook.on_after_tool_call(session_id, &call, &result_str, is_success)
                            .await?;
                    }
                    self.memory
                        .push_message(
                            session_id,
                            ChatMessage::tool_response(&call.id, &result_str),
                        )
                        .await?;
                    continue;
                }

                let target = find_tool_target(&call.name, hosts);
                let (target_host, plugin_id, actual_tool_name) = match target {
                    Some((h, pid, tname)) => (h, pid, tname),
                    None => {
                        let err_msg = format!("Tool '{}' not registered", call.name);
                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, &err_msg),
                            )
                            .await?;
                        continue;
                    }
                };

                let structured_args = match &call.arguments {
                    serde_json::Value::Object(_) => json_to_prost_struct(&call.arguments),
                    _ => None,
                };
                let tool_req = ToolCallRequest {
                    call_id: call.id.clone(),
                    tool_name: actual_tool_name,
                    session_id: session_id.to_string(),
                    payload: structured_args.map(tool_call_request::Payload::StructuredArgs),
                };

                tracing::debug!(
                    agent = %self.name,
                    tool = %call.name,
                    host_id = %target_host.host_id(),
                    plugin_id = %plugin_id,
                    "Agent stream dispatching tool RPC to host"
                );

                match target_host.call_tool(tool_req).await {
                    Ok(resp) => {
                        let is_success = resp.success;
                        let result_str = if !is_success {
                            format!("Error: {}", resp.error_message)
                        } else {
                            match resp.payload {
                                Some(tool_call_response::Payload::StructuredResult(s)) => {
                                    prost_struct_to_json(s).to_string()
                                }
                                Some(tool_call_response::Payload::RawBytes(bytes)) => {
                                    String::from_utf8_lossy(&bytes).to_string()
                                }
                                None => "{}".to_string(),
                            }
                        };
                        for hook in &self.hooks {
                            hook.on_after_tool_call(session_id, &call, &result_str, is_success)
                                .await?;
                        }
                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, result_str),
                            )
                            .await?;
                    }
                    Err(st) => {
                        let err_msg = format!("Tool RPC failed: {st}");
                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, &err_msg),
                            )
                            .await?;
                    }
                }
            }
        }

        // Final streaming generation turn (pure assistant reply)
        let messages = self.memory.get_messages(session_id).await?;
        let mut request = ChatRequest {
            model: self.config.default_model.clone(),
            messages,
            tools: Vec::new(),
            temperature: self.config.temperature,
            max_tokens: self.config.max_tokens,
        };

        for hook in &self.hooks {
            hook.on_llm_request(session_id, &mut request).await?;
        }

        let inner_stream = self.provider.chat_stream(&request).await?;
        let (tx, rx) = tokio::sync::mpsc::channel(32);
        let memory = self.memory.clone();
        let sid = session_id.to_string();
        let sm_opt = self.session_manager.clone();
        let hooks = self.hooks.clone();
        let user_toks = crate::token::estimate_text_tokens(user_input);

        tokio::spawn(async move {
            let mut inner = inner_stream;
            let mut accumulated = String::new();

            while let Some(chunk_res) = inner.next().await {
                match chunk_res {
                    Ok(chunk) => {
                        accumulated.push_str(&chunk.delta_text);
                        let is_fin = chunk.is_finished;
                        let fin_reason = chunk.finish_reason.clone();
                        let _ = tx.send(Ok(chunk)).await;
                        if is_fin {
                            if !accumulated.is_empty()
                                && let Err(e) = memory
                                    .push_message(&sid, ChatMessage::assistant(&accumulated))
                                    .await
                            {
                                tracing::error!(session_id = %sid, error = %e, "Failed to persist streaming assistant response to memory");
                            }
                            if let Some(ref sm) = sm_opt {
                                let tokens =
                                    user_toks + crate::token::estimate_text_tokens(&accumulated);
                                sm.record_turn(&sid, tokens);
                            }
                            let mut resp = crate::gateway::ChatResponse {
                                content: if accumulated.is_empty() {
                                    None
                                } else {
                                    Some(accumulated.clone())
                                },
                                tool_calls: Vec::new(),
                                finish_reason: fin_reason,
                                usage: None,
                            };
                            for hook in &hooks {
                                let _ = hook.on_llm_response(&sid, &mut resp).await;
                            }
                            return;
                        }
                    }
                    Err(e) => {
                        let _ = tx.send(Err(e)).await;
                        return;
                    }
                }
            }

            if !accumulated.is_empty()
                && let Err(e) = memory
                    .push_message(&sid, ChatMessage::assistant(&accumulated))
                    .await
            {
                tracing::error!(session_id = %sid, error = %e, "Failed to persist streaming assistant response to memory");
            }
            if let Some(ref sm) = sm_opt {
                let tokens = user_toks + crate::token::estimate_text_tokens(&accumulated);
                sm.record_turn(&sid, tokens);
            }
            let mut resp = crate::gateway::ChatResponse {
                content: if accumulated.is_empty() {
                    None
                } else {
                    Some(accumulated.clone())
                },
                tool_calls: Vec::new(),
                finish_reason: None,
                usage: None,
            };
            for hook in &hooks {
                let _ = hook.on_llm_response(&sid, &mut resp).await;
            }
        });

        Ok(Box::pin(tokio_stream::wrappers::ReceiverStream::new(rx)))
    }
}

/// Helper locating the owning host, plugin ID, and canonical tool name for an invoked tool name.
///
/// Resolves both:
/// 1. Canonical namespaced names (`<sanitized_plugin_id>__<tool_name>`).
/// 2. Bare tool names (`<tool_name>`), provided there is exactly one matching plugin.
///
/// If multiple plugins offer the same bare name and an ambiguous invocation is received,
/// returns `None` and logs an error to prevent silent, non-deterministic routing.
fn find_tool_target(
    tool_name: &str,
    hosts: &[Arc<dyn ToolHost>],
) -> Option<(Arc<dyn ToolHost>, String, String)> {
    // 1. Check for exact namespaced match first: <plugin_id>__<tool_name>
    for host in hosts {
        let metas = host.plugin_metas();
        for plugin in &metas {
            let prefix = format!(
                "{}__{}",
                crate::tool_router::sanitize_tool_identifier(&plugin.id),
                ""
            );
            if tool_name.starts_with(&prefix) {
                let base_name = &tool_name[prefix.len()..];
                for tool in &plugin.tools {
                    if tool.name == base_name {
                        return Some((host.clone(), plugin.id.clone(), tool.name.clone()));
                    }
                }
            }
        }
    }

    // 2. Search for bare tool name across all plugins
    let mut matches = Vec::new();
    for host in hosts {
        let metas = host.plugin_metas();
        for plugin in &metas {
            for tool in &plugin.tools {
                if tool.name == tool_name {
                    matches.push((host.clone(), plugin.id.clone(), tool.name.clone()));
                }
            }
        }
    }

    if matches.len() == 1 {
        Some(matches.remove(0))
    } else if matches.len() > 1 {
        tracing::error!(
            tool_name = %tool_name,
            match_count = matches.len(),
            "Ambiguous tool invocation: multiple plugins declare '{}'; invoke via namespaced name",
            tool_name
        );
        None
    } else {
        None
    }
}

/// Fluent builder for constructing customizable [`Agent`] instances.
pub struct AgentBuilder {
    name: String,
    system_prompt: Option<String>,
    provider: Arc<dyn LlmProvider>,
    memory: Option<Arc<dyn Memory>>,
    session_manager: Option<Arc<crate::session::SessionManager>>,
    persona_registry: Option<Arc<crate::prompt::PersonaRegistry>>,
    tools: Vec<Arc<dyn AgentTool>>,
    hooks: Vec<Arc<dyn AgentHook>>,
    config: AgentConfig,
    summary_config: Option<crate::summary::SummaryConfig>,
}

impl AgentBuilder {
    /// Initiates a new builder with the agent name and backend model provider.
    pub fn new(name: impl Into<String>, provider: Arc<dyn LlmProvider>) -> Self {
        Self {
            name: name.into(),
            system_prompt: None,
            provider,
            memory: None,
            session_manager: None,
            persona_registry: None,
            tools: Vec::new(),
            hooks: Vec::new(),
            config: AgentConfig::default(),
            summary_config: None,
        }
    }

    /// Sets the base persona / system prompt for the agent.
    pub fn system_prompt(mut self, prompt: impl Into<String>) -> Self {
        self.system_prompt = Some(prompt.into());
        self
    }

    /// Injects a custom memory backend (e.g. SQLite, Redis, or custom plugin memory).
    pub fn memory(mut self, memory: Arc<dyn Memory>) -> Self {
        self.memory = Some(memory);
        self
    }

    /// Injects a session manager for metadata, multi-scope keys, and turn lifecycle tracking.
    pub fn session_manager(mut self, manager: Arc<crate::session::SessionManager>) -> Self {
        self.session_manager = Some(manager);
        self
    }

    /// Injects a persona registry for dynamic persona resolution.
    pub fn persona_registry(mut self, registry: Arc<crate::prompt::PersonaRegistry>) -> Self {
        self.persona_registry = Some(registry);
        self
    }

    /// Registers a native in-process tool on this agent.
    pub fn tool(mut self, tool: impl AgentTool + 'static) -> Self {
        self.tools.push(Arc::new(tool));
        self
    }

    /// Registers a native in-process tool wrapped in an [`Arc`].
    pub fn tool_arc(mut self, tool: Arc<dyn AgentTool>) -> Self {
        self.tools.push(tool);
        self
    }

    /// Registers a lifecycle interception hook on this agent.
    pub fn hook(mut self, hook: impl AgentHook + 'static) -> Self {
        self.hooks.push(Arc::new(hook));
        self
    }

    /// Registers a lifecycle hook wrapped in an [`Arc`].
    pub fn hook_arc(mut self, hook: Arc<dyn AgentHook>) -> Self {
        self.hooks.push(hook);
        self
    }

    /// Sets default model tag.
    pub fn model(mut self, model: impl Into<String>) -> Self {
        self.config.default_model = model.into();
        self
    }

    /// Sets maximum reasoning iterations (default 5).
    pub fn max_iterations(mut self, max: usize) -> Self {
        self.config.max_iterations = max;
        self
    }

    /// Sets sampling temperature.
    pub fn temperature(mut self, temp: f32) -> Self {
        self.config.temperature = Some(temp);
        self
    }

    /// Sets max tokens.
    pub fn max_tokens(mut self, tokens: u32) -> Self {
        self.config.max_tokens = Some(tokens);
        self
    }

    /// Configures whether to stop immediately if a tool fails.
    pub fn stop_on_tool_failure(mut self, stop: bool) -> Self {
        self.config.stop_on_tool_failure = stop;
        self
    }

    /// Configures automatic long-context summary compression for this agent.
    pub fn summary_config(mut self, config: crate::summary::SummaryConfig) -> Self {
        self.summary_config = Some(config);
        self
    }

    /// Builds the configured [`Agent`].
    pub fn build(mut self) -> Agent {
        let memory = self
            .memory
            .or_else(|| self.session_manager.as_ref().map(|sm| sm.memory().clone()))
            .unwrap_or_else(|| Arc::new(SlidingWindowMemory::default()));

        if let Some(ref session_mgr) = self.session_manager
            && let Some(ref persona_reg) = self.persona_registry
        {
            // The persona hook *owns* the base system message: it overwrites the first system
            // message in place. Registered first, it can therefore never clobber a system message
            // another hook injected — a hook that appends context (the skill catalog, RAG, ...)
            // would otherwise be silently discarded whenever the session had no system prompt yet.
            self.hooks.insert(
                0,
                Arc::new(crate::prompt::DynamicPromptHook::new(
                    session_mgr.clone(),
                    persona_reg.clone(),
                )),
            );
        }

        if let Some(summary_cfg) = self.summary_config
            && summary_cfg.enabled
        {
            let summarizer = Arc::new(crate::summary::ContextSummarizer::new(
                summary_cfg,
                self.provider.clone(),
                memory.clone(),
            ));
            self.hooks
                .push(Arc::new(crate::summary::SummaryHook::new(summarizer)));
        }

        Agent {
            name: self.name,
            system_prompt: self.system_prompt,
            provider: self.provider,
            memory,
            session_manager: self.session_manager,
            persona_registry: self.persona_registry,
            tools: self.tools,
            hooks: self.hooks,
            config: self.config,
        }
    }
}
