//! Kanon Built-in Agent Engine.
//!
//! Provides a versatile, high-performance agent runtime suitable for both
//! conversational chat bots and autonomous goal-driven task agents.
//!
//! Fully modularized:
//! - Pluggable model providers implementing [`LlmProvider`];
//! - Pluggable conversational memory implementing [`Memory`];
//! - Dynamic cross-process tool calling via [`ToolHost`];
//! - Configurable recursion limits, sampling parameters, and execution policies.

use std::sync::Arc;

use kanon_proto::v1::{
    tool_call_request, tool_call_response, ToolCallRequest,
};

use crate::error::AgentError;
use crate::gateway::types::{ChatMessage, ChatRequest, Role};
use crate::gateway::LlmProvider;
use crate::memory::{Memory, SlidingWindowMemory};
use crate::tool_router::{
    aggregate_tools, json_to_prost_struct, prost_struct_to_json, ExecutedToolCall, ToolHost,
};

/// Configuration parameters for agent reasoning and execution.
#[derive(Debug, Clone)]
pub struct AgentConfig {
    /// Maximum tool reasoning loop iterations before forcing termination.
    pub max_iterations: usize,
    /// Default model identifier.
    pub default_model: String,
    /// Optional sampling temperature.
    pub temperature: Option<f32>,
    /// Optional max tokens limit for completions.
    pub max_tokens: Option<u32>,
    /// Whether to halt immediately if a tool call returns an error.
    pub stop_on_tool_failure: bool,
}

impl Default for AgentConfig {
    fn default() -> Self {
        Self {
            max_iterations: 5,
            default_model: "gpt-4o-mini".to_string(),
            temperature: None,
            max_tokens: None,
            stop_on_tool_failure: false,
        }
    }
}

/// Result produced after an agent run concludes.
#[derive(Debug, Clone, PartialEq)]
pub struct AgentOutput {
    /// Final natural language response generated by the agent.
    pub content: String,
    /// Sequence of tool calls executed during the reasoning loop.
    pub executed_tools: Vec<ExecutedToolCall>,
    /// Total conversational / reasoning turns executed.
    pub turns: usize,
    /// Model-reported finish reason (e.g. `stop`, `tool_calls`, `length`).
    pub finish_reason: Option<String>,
}

/// General-purpose Kanon Agent.
///
/// Encapsulates model backend, memory store, persona instructions, and reasoning policies.
pub struct Agent {
    /// Identifier or role name of this agent.
    name: String,
    /// Static or base system prompt setting the agent's persona and instructions.
    system_prompt: Option<String>,
    /// Provider backend for LLM completions.
    provider: Arc<dyn LlmProvider>,
    /// Pluggable memory backend for conversational history.
    memory: Arc<dyn Memory>,
    /// Operational configuration.
    config: AgentConfig,
}

impl Agent {
    /// Returns a new fluent builder for constructing an [`Agent`].
    pub fn builder(name: impl Into<String>, provider: Arc<dyn LlmProvider>) -> AgentBuilder {
        AgentBuilder::new(name, provider)
    }

    /// Agent identifier name.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Reference to the active memory backend.
    pub fn memory(&self) -> &Arc<dyn Memory> {
        &self.memory
    }

    /// Reference to the underlying provider.
    pub fn provider(&self) -> &Arc<dyn LlmProvider> {
        &self.provider
    }

    /// Active agent configuration.
    pub fn config(&self) -> &AgentConfig {
        &self.config
    }

    /// Executes the agent reasoning loop for an inbound message.
    ///
    /// # Flow:
    /// 1. Initializes session system prompt if not yet set in memory;
    /// 2. Records inbound user message in memory;
    /// 3. Dynamically queries active tools from provided plugin hosts;
    /// 4. Executes reasoning loop until model emits final text or iteration ceiling is hit;
    /// 5. Dispatches tool calls via gRPC IPC, translates parameters zero-copy, feeds results back;
    /// 6. Stores assistant reply in memory and returns [`AgentOutput`].
    pub async fn run<H: ToolHost>(
        &self,
        session_id: &str,
        user_input: &str,
        hosts: &[Arc<H>],
    ) -> Result<AgentOutput, AgentError> {
        // 1. Ensure system prompt is established for this session if configured
        if let Some(ref prompt) = self.system_prompt
            && self.memory.get_system_prompt(session_id).await.is_none()
        {
            self.memory.set_system_prompt(session_id, prompt.clone()).await;
        }

        // 2. Push user message to memory
        self.memory
            .push_message(session_id, ChatMessage::user(user_input))
            .await;

        // 3. Dynamically aggregate tools from active plugin hosts
        let tools = aggregate_tools(hosts);

        let mut executed_tools = Vec::new();
        let mut iterations = 0;

        // 4. Reasoning and tool execution loop
        loop {
            let messages = self.memory.get_messages(session_id).await;

            let request = ChatRequest {
                model: self.config.default_model.clone(),
                messages,
                tools: tools.clone(),
                temperature: self.config.temperature,
                max_tokens: self.config.max_tokens,
            };

            let response = self.provider.chat(&request).await?;

            // Terminal state: Model completed generation without requesting tools
            if response.tool_calls.is_empty() {
                let final_content = response.content.unwrap_or_default();
                if !final_content.is_empty() {
                    self.memory
                        .push_message(session_id, ChatMessage::assistant(&final_content))
                        .await;
                }
                return Ok(AgentOutput {
                    content: final_content,
                    executed_tools,
                    turns: iterations + 1,
                    finish_reason: response.finish_reason,
                });
            }

            // Guard against runaway loop recursion
            if iterations >= self.config.max_iterations {
                tracing::warn!(
                    agent = %self.name,
                    session_id = %session_id,
                    iterations = iterations,
                    "Agent reasoning iteration ceiling reached; breaking loop"
                );
                let fallback = response.content.unwrap_or_else(|| {
                    "Agent reasoning recursion limit reached; execution terminated.".to_string()
                });
                self.memory
                    .push_message(session_id, ChatMessage::assistant(&fallback))
                    .await;
                return Ok(AgentOutput {
                    content: fallback,
                    executed_tools,
                    turns: iterations + 1,
                    finish_reason: Some("max_iterations".to_string()),
                });
            }

            iterations += 1;

            // Record assistant tool calls turn into history
            self.memory
                .push_message(
                    session_id,
                    ChatMessage {
                        role: Role::Assistant,
                        content: response.content.clone(),
                        tool_calls: Some(response.tool_calls.clone()),
                        tool_call_id: None,
                        name: None,
                    },
                )
                .await;

            // Execute each requested tool call
            for call in response.tool_calls {
                let target = find_tool_target(&call.name, hosts);

                let (target_host, plugin_id) = match target {
                    Some((h, pid)) => (h, pid),
                    None => {
                        tracing::warn!(tool = %call.name, "Requested tool not declared by any active host");
                        let err_msg = format!("Tool '{}' not registered", call.name);
                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, &err_msg),
                            )
                            .await;
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id,
                            tool_name: call.name.clone(),
                            plugin_id: "unknown".to_string(),
                            host_id: "unknown".to_string(),
                            success: false,
                        });
                        if self.config.stop_on_tool_failure {
                            return Err(AgentError::ToolNotFound(call.name));
                        }
                        continue;
                    }
                };

                // Zero-copy in-memory translation from serde_json::Value to prost_types::Struct
                let structured_args = match &call.arguments {
                    serde_json::Value::Object(_) => json_to_prost_struct(&call.arguments),
                    _ => None,
                };

                let tool_req = ToolCallRequest {
                    call_id: call.id.clone(),
                    tool_name: call.name.clone(),
                    session_id: session_id.to_string(),
                    payload: structured_args.map(tool_call_request::Payload::StructuredArgs),
                };

                tracing::debug!(
                    agent = %self.name,
                    tool = %call.name,
                    host_id = %target_host.host_id(),
                    plugin_id = %plugin_id,
                    "Agent dispatching tool RPC to host"
                );

                match target_host.call_tool(tool_req).await {
                    Ok(resp) => {
                        let is_success = resp.success;
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id.clone(),
                            tool_name: call.name.clone(),
                            plugin_id: plugin_id.clone(),
                            host_id: target_host.host_id().to_string(),
                            success: is_success,
                        });

                        let result_str = if !is_success {
                            format!("Error: {}", resp.error_message)
                        } else {
                            match resp.payload {
                                Some(tool_call_response::Payload::StructuredResult(s)) => {
                                    prost_struct_to_json(s).to_string()
                                }
                                Some(tool_call_response::Payload::RawBytes(bytes)) => {
                                    String::from_utf8_lossy(&bytes).to_string()
                                }
                                None => "{}".to_string(),
                            }
                        };

                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(&call.id, result_str),
                            )
                            .await;

                        if !is_success && self.config.stop_on_tool_failure {
                            tracing::warn!(tool = %call.name, "Tool reported failure and stop_on_tool_failure is enabled");
                            break;
                        }
                    }
                    Err(status) => {
                        tracing::error!(tool = %call.name, error = %status, "Tool RPC execution failed");
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id.clone(),
                            tool_name: call.name.clone(),
                            plugin_id: plugin_id.clone(),
                            host_id: target_host.host_id().to_string(),
                            success: false,
                        });

                        self.memory
                            .push_message(
                                session_id,
                                ChatMessage::tool_response(
                                    &call.id,
                                    format!("RPC Error: {}", status.message()),
                                ),
                            )
                            .await;

                        if self.config.stop_on_tool_failure {
                            return Err(AgentError::from(status));
                        }
                    }
                }
            }
        }
    }
}

/// Helper locating the owning host and plugin ID for a tool name.
fn find_tool_target<H: ToolHost>(tool_name: &str, hosts: &[Arc<H>]) -> Option<(Arc<H>, String)> {
    for host in hosts {
        for plugin in host.plugin_metas() {
            for tool in &plugin.tools {
                if tool.name == tool_name {
                    return Some((host.clone(), plugin.id.clone()));
                }
            }
        }
    }
    None
}

/// Fluent builder for constructing customizable [`Agent`] instances.
pub struct AgentBuilder {
    name: String,
    system_prompt: Option<String>,
    provider: Arc<dyn LlmProvider>,
    memory: Option<Arc<dyn Memory>>,
    config: AgentConfig,
}

impl AgentBuilder {
    /// Initiates a new builder with the agent name and backend model provider.
    pub fn new(name: impl Into<String>, provider: Arc<dyn LlmProvider>) -> Self {
        Self {
            name: name.into(),
            system_prompt: None,
            provider,
            memory: None,
            config: AgentConfig::default(),
        }
    }

    /// Sets the base persona / system prompt for the agent.
    pub fn system_prompt(mut self, prompt: impl Into<String>) -> Self {
        self.system_prompt = Some(prompt.into());
        self
    }

    /// Injects a custom memory backend (e.g. SQLite, Redis, or custom plugin memory).
    pub fn memory(mut self, memory: Arc<dyn Memory>) -> Self {
        self.memory = Some(memory);
        self
    }

    /// Sets default model tag.
    pub fn model(mut self, model: impl Into<String>) -> Self {
        self.config.default_model = model.into();
        self
    }

    /// Sets maximum reasoning iterations (default 5).
    pub fn max_iterations(mut self, max: usize) -> Self {
        self.config.max_iterations = max;
        self
    }

    /// Sets sampling temperature.
    pub fn temperature(mut self, temp: f32) -> Self {
        self.config.temperature = Some(temp);
        self
    }

    /// Sets max tokens.
    pub fn max_tokens(mut self, tokens: u32) -> Self {
        self.config.max_tokens = Some(tokens);
        self
    }

    /// Builds the configured [`Agent`].
    pub fn build(self) -> Agent {
        let memory = self
            .memory
            .unwrap_or_else(|| Arc::new(SlidingWindowMemory::default()));

        Agent {
            name: self.name,
            system_prompt: self.system_prompt,
            provider: self.provider,
            memory,
            config: self.config,
        }
    }
}
