//! Cross-language Tool Calling state machine router and execution loop.
//!
//! Bridges LLM function calling with out-of-process plugin hosts via gRPC.
//! Dynamically aggregates tool definitions from active plugin hosts, translates
//! arguments between `prost_types::Struct` and `serde_json::Value` without
//! redundant string serialization, dispatches tool execution over IPC, and feeds
//! execution results back to the model with loop recursion protection.

use std::sync::Arc;
use async_trait::async_trait;

use kanon_proto::v1::{
    tool_call_request, tool_call_response, PluginMeta, ToolCallRequest, ToolCallResponse, ToolMeta,
};

use crate::error::ToolRouterError;
use crate::gateway::types::{ChatMessage, ChatRequest, Role, ToolDefinition};
use crate::gateway::LlmProvider;
use crate::memory::ConversationManager;

/// Abstract interface for a plugin host capable of executing tool calls.
///
/// Implemented by `ManagedHost` in `kanon-core` and mock hosts in unit tests.
#[async_trait]
pub trait ToolHost: Send + Sync {
    /// Unique identifier of the host process (e.g. `host_demo_rust`).
    fn host_id(&self) -> &str;

    /// Metadata descriptors of all plugins running on this host.
    fn plugin_metas(&self) -> &[PluginMeta];

    /// Invokes a declared tool on this host via gRPC IPC.
    async fn call_tool(&self, req: ToolCallRequest) -> Result<ToolCallResponse, tonic::Status>;
}

/// Record of an executed tool call, useful for audit logging and verification.
#[derive(Debug, Clone, PartialEq)]
pub struct ExecutedToolCall {
    /// Unique call identifier allocated by the provider.
    pub call_id: String,
    /// Function name of the tool called.
    pub tool_name: String,
    /// Plugin identifier hosting the tool.
    pub plugin_id: String,
    /// Host process identifier running the plugin.
    pub host_id: String,
    /// Execution status returned by the tool handler.
    pub success: bool,
}

/// Output produced by the tool router execution loop.
#[derive(Debug, Clone, PartialEq)]
pub struct ToolRouterOutput {
    /// Final natural language response generated by the model.
    pub content: String,
    /// Audit sequence of all tool calls executed across reasoning turns.
    pub executed_tools: Vec<ExecutedToolCall>,
}

/// Resolved target identifying where a tool should be routed.
struct ResolvedToolTarget<H: ToolHost> {
    host: Arc<H>,
    plugin_id: String,
    #[allow(dead_code)]
    meta: ToolMeta,
}

impl<H: ToolHost> ResolvedToolTarget<H> {
    /// Locates the host and plugin owning the specified tool name among active hosts.
    fn find(tool_name: &str, hosts: &[Arc<H>]) -> Option<Self> {
        for host in hosts {
            for plugin in host.plugin_metas() {
                for tool in &plugin.tools {
                    if tool.name == tool_name {
                        return Some(Self {
                            host: host.clone(),
                            plugin_id: plugin.id.clone(),
                            meta: tool.clone(),
                        });
                    }
                }
            }
        }
        None
    }
}

/// Dynamically aggregates tool definitions declared across all active plugin hosts.
///
/// Directly translates Protobuf Struct schemas into `serde_json::Value` in memory.
pub fn aggregate_tools<H: ToolHost>(hosts: &[Arc<H>]) -> Vec<ToolDefinition> {
    let mut definitions = Vec::new();
    for host in hosts {
        for plugin in host.plugin_metas() {
            for tool in &plugin.tools {
                let parameters = match &tool.parameters {
                    Some(s) => prost_struct_to_json(s.clone()),
                    None => serde_json::json!({
                        "type": "object",
                        "properties": {}
                    }),
                };

                definitions.push(ToolDefinition {
                    name: tool.name.clone(),
                    description: tool.description.clone(),
                    parameters,
                });
            }
        }
    }
    definitions
}

/// Central Tool Calling state machine router and execution loop.
pub struct ToolRouter {
    gateway: Arc<dyn LlmProvider>,
    memory: Arc<ConversationManager>,
    default_model: String,
    max_tool_iterations: usize,
}

impl ToolRouter {
    /// Default maximum reasoning turns allowed to prevent runaway tool loops.
    pub const DEFAULT_MAX_ITERATIONS: usize = 2;

    /// Creates a new `ToolRouter` with default maximum iterations (2 turns).
    pub fn new(
        gateway: Arc<dyn LlmProvider>,
        memory: Arc<ConversationManager>,
        default_model: impl Into<String>,
    ) -> Self {
        Self {
            gateway,
            memory,
            default_model: default_model.into(),
            max_tool_iterations: Self::DEFAULT_MAX_ITERATIONS,
        }
    }

    /// Overrides the maximum tool execution loop iterations.
    pub fn with_max_iterations(mut self, max: usize) -> Self {
        self.max_tool_iterations = max;
        self
    }

    /// Returns a reference to the conversation manager.
    pub fn memory(&self) -> &Arc<ConversationManager> {
        &self.memory
    }

    /// Executes the tool calling loop for an incoming conversational message.
    ///
    /// # State Machine Workflow:
    /// 1. Appends the inbound user message to conversation memory.
    /// 2. Discovers all tools dynamically declared by currently active plugin hosts.
    /// 3. In a loop bounded by `max_tool_iterations`:
    ///    - Submits the conversational history + tools contract to the LLM backend.
    ///    - If the model returns text without tool calls: stores response and returns.
    ///    - If the model requests `tool_calls`:
    ///      - Verifies recursion guard limit; halts if exceeded.
    ///      - For each requested tool, resolves the owning host and converts arguments
    ///        directly to `prost_types::Struct` in-memory.
    ///      - Dispatches `ToolCallRequest` via gRPC IPC to the plugin host.
    ///      - Appends the tool execution result into memory as a `Role::Tool` message.
    ///    - Repeats the cycle so the model can reason over the tool execution output.
    pub async fn execute<H: ToolHost>(
        &self,
        session_id: &str,
        user_input: &str,
        hosts: &[Arc<H>],
    ) -> Result<ToolRouterOutput, ToolRouterError> {
        // 1. Record user message in conversational memory
        self.memory.push_message(session_id, ChatMessage::user(user_input));

        // 2. Dynamically aggregate tools from active plugin hosts
        let tools = aggregate_tools(hosts);

        let mut executed_tools = Vec::new();
        let mut iterations = 0;

        // 3. State machine reasoning & tool execution loop
        loop {
            let messages = self.memory.get_messages(session_id);

            let request = ChatRequest {
                model: self.default_model.clone(),
                messages,
                tools: tools.clone(),
                temperature: None,
                max_tokens: None,
            };

            let response = self.gateway.chat(&request).await?;

            // Terminal state: Model completed inference without requesting further tools
            if response.tool_calls.is_empty() {
                let final_content = response.content.unwrap_or_default();
                if !final_content.is_empty() {
                    self.memory.push_message(session_id, ChatMessage::assistant(&final_content));
                }
                return Ok(ToolRouterOutput {
                    content: final_content,
                    executed_tools,
                });
            }

            // Guard against runaway loop recursion
            if iterations >= self.max_tool_iterations {
                tracing::warn!(
                    session_id = %session_id,
                    iterations = iterations,
                    "Tool calling recursion limit reached; terminating execution loop"
                );
                let fallback = response.content.unwrap_or_else(|| {
                    "Tool calling recursion limit reached; execution halted.".to_string()
                });
                self.memory.push_message(session_id, ChatMessage::assistant(&fallback));
                return Ok(ToolRouterOutput {
                    content: fallback,
                    executed_tools,
                });
            }

            iterations += 1;

            // Record assistant message with tool calls in history
            self.memory.push_message(
                session_id,
                ChatMessage {
                    role: Role::Assistant,
                    content: response.content.clone(),
                    tool_calls: Some(response.tool_calls.clone()),
                    tool_call_id: None,
                    name: None,
                },
            );

            // Execute each requested tool call
            for call in response.tool_calls {
                let target = match ResolvedToolTarget::find(&call.name, hosts) {
                    Some(t) => t,
                    None => {
                        tracing::warn!(tool = %call.name, "Requested tool not declared by any active host");
                        let err_msg = format!("Tool '{}' not registered", call.name);
                        self.memory.push_message(
                            session_id,
                            ChatMessage::tool_response(&call.id, &err_msg),
                        );
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id,
                            tool_name: call.name,
                            plugin_id: "unknown".to_string(),
                            host_id: "unknown".to_string(),
                            success: false,
                        });
                        continue;
                    }
                };

                // Zero-copy direct translation from serde_json::Value to prost_types::Struct
                let structured_args = match &call.arguments {
                    serde_json::Value::Object(_) => json_to_prost_struct(&call.arguments),
                    _ => None,
                };

                let tool_req = ToolCallRequest {
                    call_id: call.id.clone(),
                    tool_name: call.name.clone(),
                    session_id: session_id.to_string(),
                    payload: structured_args.map(tool_call_request::Payload::StructuredArgs),
                };

                tracing::debug!(
                    tool = %call.name,
                    host_id = %target.host.host_id(),
                    plugin_id = %target.plugin_id,
                    "Calling tool on target host via IPC"
                );

                match target.host.call_tool(tool_req).await {
                    Ok(resp) => {
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id.clone(),
                            tool_name: call.name.clone(),
                            plugin_id: target.plugin_id.clone(),
                            host_id: target.host.host_id().to_string(),
                            success: resp.success,
                        });

                        // Format tool result payload for model ingestion
                        let result_str = if !resp.success {
                            format!("Error: {}", resp.error_message)
                        } else {
                            match resp.payload {
                                Some(tool_call_response::Payload::StructuredResult(s)) => {
                                    prost_struct_to_json(s).to_string()
                                }
                                Some(tool_call_response::Payload::RawBytes(bytes)) => {
                                    String::from_utf8_lossy(&bytes).to_string()
                                }
                                None => "{}".to_string(),
                            }
                        };

                        self.memory.push_message(
                            session_id,
                            ChatMessage::tool_response(&call.id, result_str),
                        );
                    }
                    Err(status) => {
                        tracing::error!(
                            tool = %call.name,
                            error = %status,
                            "Tool execution failed with gRPC status"
                        );
                        executed_tools.push(ExecutedToolCall {
                            call_id: call.id.clone(),
                            tool_name: call.name.clone(),
                            plugin_id: target.plugin_id.clone(),
                            host_id: target.host.host_id().to_string(),
                            success: false,
                        });
                        self.memory.push_message(
                            session_id,
                            ChatMessage::tool_response(
                                &call.id,
                                format!("RPC Error: {}", status.message()),
                            ),
                        );
                    }
                }
            }
        }
    }
}

// =========================================================================
// In-Memory Protobuf Struct <-> Serde JSON Direct Conversion
// =========================================================================

/// Directly converts a [`prost_types::Struct`] into a [`serde_json::Value`].
///
/// Avoids intermediate JSON string encoding/decoding, preserving performance.
pub fn prost_struct_to_json(s: prost_types::Struct) -> serde_json::Value {
    let mut map = serde_json::Map::with_capacity(s.fields.len());
    for (k, v) in s.fields {
        map.insert(k, prost_value_to_json(v));
    }
    serde_json::Value::Object(map)
}

/// Converts a [`prost_types::Value`] into its corresponding [`serde_json::Value`].
pub fn prost_value_to_json(v: prost_types::Value) -> serde_json::Value {
    match v.kind {
        Some(prost_types::value::Kind::NullValue(_)) | None => serde_json::Value::Null,
        Some(prost_types::value::Kind::NumberValue(n)) => serde_json::Number::from_f64(n)
            .map(serde_json::Value::Number)
            .unwrap_or(serde_json::Value::Null),
        Some(prost_types::value::Kind::StringValue(s)) => serde_json::Value::String(s),
        Some(prost_types::value::Kind::BoolValue(b)) => serde_json::Value::Bool(b),
        Some(prost_types::value::Kind::StructValue(s)) => prost_struct_to_json(s),
        Some(prost_types::value::Kind::ListValue(l)) => {
            serde_json::Value::Array(l.values.into_iter().map(prost_value_to_json).collect())
        }
    }
}

/// Directly converts a [`serde_json::Value`] object into a [`prost_types::Struct`].
///
/// Returns `None` if the input is not a JSON object (`Value::Object`).
pub fn json_to_prost_struct(val: &serde_json::Value) -> Option<prost_types::Struct> {
    let map = val.as_object()?;
    let mut fields = std::collections::BTreeMap::new();
    for (k, v) in map {
        fields.insert(k.clone(), json_to_prost_value(v));
    }
    Some(prost_types::Struct { fields })
}

/// Converts a [`serde_json::Value`] into its corresponding [`prost_types::Value`].
pub fn json_to_prost_value(val: &serde_json::Value) -> prost_types::Value {
    let kind = match val {
        serde_json::Value::Null => Some(prost_types::value::Kind::NullValue(0)),
        serde_json::Value::Bool(b) => Some(prost_types::value::Kind::BoolValue(*b)),
        serde_json::Value::Number(n) => {
            Some(prost_types::value::Kind::NumberValue(n.as_f64().unwrap_or(0.0)))
        }
        serde_json::Value::String(s) => Some(prost_types::value::Kind::StringValue(s.clone())),
        serde_json::Value::Array(arr) => {
            let values = arr.iter().map(json_to_prost_value).collect();
            Some(prost_types::value::Kind::ListValue(prost_types::ListValue { values }))
        }
        serde_json::Value::Object(map) => {
            let mut fields = std::collections::BTreeMap::new();
            for (k, v) in map {
                fields.insert(k.clone(), json_to_prost_value(v));
            }
            Some(prost_types::value::Kind::StructValue(prost_types::Struct { fields }))
        }
    };
    prost_types::Value { kind }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prost_json_roundtrip() {
        let json_input = serde_json::json!({
            "name": "calc",
            "count": 42.0,
            "active": true,
            "nested": {
                "tags": ["rust", "plugin"]
            }
        });

        let prost_struct = json_to_prost_struct(&json_input).expect("Valid JSON object");
        let json_output = prost_struct_to_json(prost_struct);

        assert_eq!(json_input, json_output);
    }
}
