//! Cross-language Tool Calling state machine router and execution loop.
//!
//! Bridges LLM function calling with out-of-process plugin hosts via gRPC.
//! Dynamically aggregates tool definitions from active plugin hosts, translates
//! arguments between `prost_types::Struct` and `serde_json::Value` without
//! redundant string serialization, dispatches tool execution over IPC, and feeds
//! execution results back to the model with loop recursion protection.

use async_trait::async_trait;
use std::sync::Arc;

use kanon_proto::v1::{PluginMeta, ToolCallRequest, ToolCallResponse};

use crate::agent::Agent;
use crate::error::{AgentError, ToolRouterError};
use crate::gateway::LlmProvider;
use crate::gateway::types::ToolDefinition;
use crate::memory::Memory;

/// Abstract interface for a plugin host capable of executing tool calls.
///
/// Implemented by `ManagedHost` in `kanon-core` and mock hosts in unit tests.
#[async_trait]
#[async_trait::async_trait]
pub trait ToolHost: Send + Sync {
    /// Unique identifier of the host process (e.g. `host_demo_rust`).
    fn host_id(&self) -> &str;

    /// Metadata descriptors of all plugins (or MCP servers) reachable through this host.
    ///
    /// Returned by value: a host whose tool list is refreshed at runtime (an MCP server whose
    /// connection is re-established) cannot hand out a borrowed slice of lock-guarded state.
    fn plugin_metas(&self) -> Vec<PluginMeta>;

    /// Invokes a declared tool on this host via gRPC IPC.
    async fn call_tool(&self, req: ToolCallRequest) -> Result<ToolCallResponse, tonic::Status>;
}

/// Record of an executed tool call, useful for audit logging and verification.
#[derive(Debug, Clone, PartialEq)]
pub struct ExecutedToolCall {
    /// Unique call identifier allocated by the provider.
    pub call_id: String,
    /// Function name of the tool called.
    pub tool_name: String,
    /// Plugin identifier hosting the tool.
    pub plugin_id: String,
    /// Host process identifier running the plugin.
    pub host_id: String,
    /// Execution status returned by the tool handler.
    pub success: bool,
}

/// Output produced by the tool router execution loop.
#[derive(Debug, Clone, PartialEq)]
pub struct ToolRouterOutput {
    /// Final natural language response generated by the model.
    pub content: String,
    /// Audit sequence of all tool calls executed across reasoning turns.
    pub executed_tools: Vec<ExecutedToolCall>,
}

/// Sanitizes a plugin identifier so it is compliant with model tool naming constraints.
/// Both OpenAI and Anthropic require tool names to adhere to `^[a-zA-Z0-9_-]{1,64}$`.
pub fn sanitize_tool_identifier(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Constructs the canonical namespaced tool name for a plugin tool:
/// `<sanitized_plugin_id>__<tool_name>`
pub fn namespaced_tool_name(plugin_id: &str, tool_name: &str) -> String {
    format!("{}__{}", sanitize_tool_identifier(plugin_id), tool_name)
}

/// Dynamically aggregates tool definitions declared across all active plugin hosts.
///
/// Prevents name collision: if multiple plugins declare tools with identical names,
/// they are automatically disambiguated with namespacing (`<plugin_id>__<tool_name>`).
pub fn aggregate_tools(hosts: &[Arc<dyn ToolHost>]) -> Vec<ToolDefinition> {
    // 1. First pass: count tool name occurrences across all plugins
    let mut name_counts: std::collections::HashMap<String, usize> =
        std::collections::HashMap::new();
    for host in hosts {
        let metas = host.plugin_metas();
        for plugin in &metas {
            for tool in &plugin.tools {
                *name_counts.entry(tool.name.clone()).or_insert(0) += 1;
            }
        }
    }

    // 2. Second pass: build definitions, namespacing any collided names
    let mut definitions = Vec::new();
    for host in hosts {
        let metas = host.plugin_metas();
        for plugin in &metas {
            for tool in &plugin.tools {
                let parameters = match &tool.parameters {
                    Some(s) => prost_struct_to_json(s.clone()),
                    None => serde_json::json!({
                        "type": "object",
                        "properties": {}
                    }),
                };

                let is_duplicate = name_counts.get(&tool.name).copied().unwrap_or(0) > 1;
                let (resolved_name, description) = if is_duplicate {
                    let ns_name = namespaced_tool_name(&plugin.id, &tool.name);
                    tracing::warn!(
                        tool_name = %tool.name,
                        plugin_id = %plugin.id,
                        namespaced = %ns_name,
                        "Duplicate tool name across plugins; disambiguated via namespacing"
                    );
                    (
                        ns_name,
                        format!("{} (plugin: {})", tool.description, plugin.id),
                    )
                } else {
                    (tool.name.clone(), tool.description.clone())
                };

                definitions.push(ToolDefinition {
                    name: resolved_name,
                    description,
                    parameters,
                });
            }
        }
    }
    definitions
}

/// Central Tool Calling state machine router and execution loop.
///
/// Serves as a specialized adapter around the core [`Agent`] engine for pipeline integration.
#[derive(Clone)]
pub struct ToolRouter {
    agent: Arc<Agent>,
}

impl ToolRouter {
    /// Default maximum reasoning turns allowed to prevent runaway tool loops.
    pub const DEFAULT_MAX_ITERATIONS: usize = 2;

    /// Creates a new `ToolRouter` with default maximum iterations (2 turns).
    pub fn new<M: Memory + 'static>(
        gateway: Arc<dyn LlmProvider>,
        memory: Arc<M>,
        default_model: impl Into<String>,
    ) -> Self {
        let agent = Agent::builder("tool_router", gateway)
            .memory(memory as Arc<dyn Memory>)
            .model(default_model)
            .max_iterations(Self::DEFAULT_MAX_ITERATIONS)
            .build();
        Self {
            agent: Arc::new(agent),
        }
    }

    /// Creates a `ToolRouter` wrapping an existing shared [`Agent`].
    pub fn from_arc(agent: Arc<Agent>) -> Self {
        Self { agent }
    }

    /// Creates a `ToolRouter` wrapping an existing [`Agent`].
    pub fn from_agent(agent: Agent) -> Self {
        Self {
            agent: Arc::new(agent),
        }
    }

    /// Overrides the maximum tool execution loop iterations.
    pub fn with_max_iterations(mut self, max: usize) -> Self {
        let mut builder = Agent::builder(self.agent.name(), self.agent.provider().clone())
            .memory(self.agent.memory().clone())
            .model(&self.agent.config().default_model)
            .max_iterations(max)
            .stop_on_tool_failure(self.agent.config().stop_on_tool_failure);

        if let Some(sm) = self.agent.session_manager() {
            builder = builder.session_manager(sm.clone());
        }
        if let Some(pr) = self.agent.persona_registry() {
            builder = builder.persona_registry(pr.clone());
        }
        if let Some(temp) = self.agent.config().temperature {
            builder = builder.temperature(temp);
        }
        if let Some(tokens) = self.agent.config().max_tokens {
            builder = builder.max_tokens(tokens);
        }
        for hook in self.agent.hooks() {
            builder = builder.hook_arc(hook.clone());
        }
        for tool in self.agent.tools() {
            builder = builder.tool_arc(tool.clone());
        }

        self.agent = Arc::new(builder.build());
        self
    }

    /// Returns a reference to the active memory backend.
    pub fn memory(&self) -> &Arc<dyn Memory> {
        self.agent.memory()
    }

    /// Access to the underlying [`Agent`] engine.
    pub fn agent(&self) -> &Agent {
        &self.agent
    }

    /// Returns a cloned `Arc` of the underlying [`Agent`] engine.
    pub fn agent_arc(&self) -> Arc<Agent> {
        Arc::clone(&self.agent)
    }

    /// Executes the tool calling loop for an incoming conversational message.
    pub async fn execute(
        &self,
        session_id: &str,
        user_input: &str,
        hosts: &[Arc<dyn ToolHost>],
    ) -> Result<ToolRouterOutput, ToolRouterError> {
        match self.agent.run(session_id, user_input, hosts).await {
            Ok(output) => Ok(ToolRouterOutput {
                content: output.content,
                executed_tools: output.executed_tools,
            }),
            Err(AgentError::Gateway(e)) => Err(ToolRouterError::Gateway(e)),
            Err(AgentError::Rpc(s)) => Err(ToolRouterError::Rpc(s)),
            Err(AgentError::ToolNotFound(name)) => Err(ToolRouterError::ToolNotFound(name)),
            Err(AgentError::Memory(m)) => Err(ToolRouterError::Gateway(
                crate::error::GatewayError::InvalidResponse(m),
            )),
        }
    }
}

// =========================================================================
// In-Memory Protobuf Struct <-> Serde JSON Direct Conversion
// =========================================================================

/// Directly converts a [`prost_types::Struct`] into a [`serde_json::Value`].
///
/// Avoids intermediate JSON string encoding/decoding, preserving performance.
pub fn prost_struct_to_json(s: prost_types::Struct) -> serde_json::Value {
    let mut map = serde_json::Map::with_capacity(s.fields.len());
    for (k, v) in s.fields {
        map.insert(k, prost_value_to_json(v));
    }
    serde_json::Value::Object(map)
}

/// Converts a [`prost_types::Value`] into its corresponding [`serde_json::Value`].
pub fn prost_value_to_json(v: prost_types::Value) -> serde_json::Value {
    match v.kind {
        Some(prost_types::value::Kind::NullValue(_)) | None => serde_json::Value::Null,
        Some(prost_types::value::Kind::NumberValue(n)) => serde_json::Number::from_f64(n)
            .map(serde_json::Value::Number)
            .unwrap_or(serde_json::Value::Null),
        Some(prost_types::value::Kind::StringValue(s)) => serde_json::Value::String(s),
        Some(prost_types::value::Kind::BoolValue(b)) => serde_json::Value::Bool(b),
        Some(prost_types::value::Kind::StructValue(s)) => prost_struct_to_json(s),
        Some(prost_types::value::Kind::ListValue(l)) => {
            serde_json::Value::Array(l.values.into_iter().map(prost_value_to_json).collect())
        }
    }
}

/// Directly converts a [`serde_json::Value`] object into a [`prost_types::Struct`].
///
/// Returns `None` if the input is not a JSON object (`Value::Object`).
pub fn json_to_prost_struct(val: &serde_json::Value) -> Option<prost_types::Struct> {
    let map = val.as_object()?;
    let mut fields = std::collections::BTreeMap::new();
    for (k, v) in map {
        fields.insert(k.clone(), json_to_prost_value(v));
    }
    Some(prost_types::Struct { fields })
}

/// Converts a [`serde_json::Value`] into its corresponding [`prost_types::Value`].
pub fn json_to_prost_value(val: &serde_json::Value) -> prost_types::Value {
    let kind = match val {
        serde_json::Value::Null => Some(prost_types::value::Kind::NullValue(0)),
        serde_json::Value::Bool(b) => Some(prost_types::value::Kind::BoolValue(*b)),
        serde_json::Value::Number(n) => Some(prost_types::value::Kind::NumberValue(
            n.as_f64().unwrap_or(0.0),
        )),
        serde_json::Value::String(s) => Some(prost_types::value::Kind::StringValue(s.clone())),
        serde_json::Value::Array(arr) => {
            let values = arr.iter().map(json_to_prost_value).collect();
            Some(prost_types::value::Kind::ListValue(
                prost_types::ListValue { values },
            ))
        }
        serde_json::Value::Object(map) => {
            let mut fields = std::collections::BTreeMap::new();
            for (k, v) in map {
                fields.insert(k.clone(), json_to_prost_value(v));
            }
            Some(prost_types::value::Kind::StructValue(prost_types::Struct {
                fields,
            }))
        }
    };
    prost_types::Value { kind }
}
