//! Cross-language Tool Calling state machine router and execution loop.
//!
//! Bridges LLM function calling with out-of-process plugin hosts via gRPC.
//! Dynamically aggregates tool definitions from active plugin hosts, translates
//! arguments between `prost_types::Struct` and `serde_json::Value` without
//! redundant string serialization, dispatches tool execution over IPC, and feeds
//! execution results back to the model with loop recursion protection.

use std::sync::Arc;
use async_trait::async_trait;

use kanon_proto::v1::{PluginMeta, ToolCallRequest, ToolCallResponse};

use crate::agent::Agent;
use crate::error::{AgentError, ToolRouterError};
use crate::gateway::types::ToolDefinition;
use crate::gateway::LlmProvider;
use crate::memory::Memory;

/// Abstract interface for a plugin host capable of executing tool calls.
///
/// Implemented by `ManagedHost` in `kanon-core` and mock hosts in unit tests.
#[async_trait]
pub trait ToolHost: Send + Sync {
    /// Unique identifier of the host process (e.g. `host_demo_rust`).
    fn host_id(&self) -> &str;

    /// Metadata descriptors of all plugins running on this host.
    fn plugin_metas(&self) -> &[PluginMeta];

    /// Invokes a declared tool on this host via gRPC IPC.
    async fn call_tool(&self, req: ToolCallRequest) -> Result<ToolCallResponse, tonic::Status>;
}

/// Record of an executed tool call, useful for audit logging and verification.
#[derive(Debug, Clone, PartialEq)]
pub struct ExecutedToolCall {
    /// Unique call identifier allocated by the provider.
    pub call_id: String,
    /// Function name of the tool called.
    pub tool_name: String,
    /// Plugin identifier hosting the tool.
    pub plugin_id: String,
    /// Host process identifier running the plugin.
    pub host_id: String,
    /// Execution status returned by the tool handler.
    pub success: bool,
}

/// Output produced by the tool router execution loop.
#[derive(Debug, Clone, PartialEq)]
pub struct ToolRouterOutput {
    /// Final natural language response generated by the model.
    pub content: String,
    /// Audit sequence of all tool calls executed across reasoning turns.
    pub executed_tools: Vec<ExecutedToolCall>,
}

/// Dynamically aggregates tool definitions declared across all active plugin hosts.
///
/// Directly translates Protobuf Struct schemas into `serde_json::Value` in memory.
pub fn aggregate_tools<H: ToolHost>(hosts: &[Arc<H>]) -> Vec<ToolDefinition> {
    let mut definitions = Vec::new();
    for host in hosts {
        for plugin in host.plugin_metas() {
            for tool in &plugin.tools {
                let parameters = match &tool.parameters {
                    Some(s) => prost_struct_to_json(s.clone()),
                    None => serde_json::json!({
                        "type": "object",
                        "properties": {}
                    }),
                };

                definitions.push(ToolDefinition {
                    name: tool.name.clone(),
                    description: tool.description.clone(),
                    parameters,
                });
            }
        }
    }
    definitions
}

/// Central Tool Calling state machine router and execution loop.
///
/// Serves as a specialized adapter around the core [`Agent`] engine for pipeline integration.
pub struct ToolRouter {
    agent: Agent,
}

impl ToolRouter {
    /// Default maximum reasoning turns allowed to prevent runaway tool loops.
    pub const DEFAULT_MAX_ITERATIONS: usize = 2;

    /// Creates a new `ToolRouter` with default maximum iterations (2 turns).
    pub fn new<M: Memory + 'static>(
        gateway: Arc<dyn LlmProvider>,
        memory: Arc<M>,
        default_model: impl Into<String>,
    ) -> Self {
        let agent = Agent::builder("tool_router", gateway)
            .memory(memory as Arc<dyn Memory>)
            .model(default_model)
            .max_iterations(Self::DEFAULT_MAX_ITERATIONS)
            .build();
        Self { agent }
    }

    /// Overrides the maximum tool execution loop iterations.
    pub fn with_max_iterations(mut self, max: usize) -> Self {
        self.agent = Agent::builder(self.agent.name(), self.agent.provider().clone())
            .memory(self.agent.memory().clone())
            .model(&self.agent.config().default_model)
            .max_iterations(max)
            .build();
        self
    }

    /// Returns a reference to the active memory backend.
    pub fn memory(&self) -> &Arc<dyn Memory> {
        self.agent.memory()
    }

    /// Access to the underlying [`Agent`] engine.
    pub fn agent(&self) -> &Agent {
        &self.agent
    }

    /// Executes the tool calling loop for an incoming conversational message.
    pub async fn execute<H: ToolHost>(
        &self,
        session_id: &str,
        user_input: &str,
        hosts: &[Arc<H>],
    ) -> Result<ToolRouterOutput, ToolRouterError> {
        match self.agent.run(session_id, user_input, hosts).await {
            Ok(output) => Ok(ToolRouterOutput {
                content: output.content,
                executed_tools: output.executed_tools,
            }),
            Err(AgentError::Gateway(e)) => Err(ToolRouterError::Gateway(e)),
            Err(AgentError::Rpc(s)) => Err(ToolRouterError::Rpc(s)),
            Err(AgentError::ToolNotFound(name)) => Err(ToolRouterError::ToolNotFound(name)),
            Err(AgentError::Memory(m)) => {
                Err(ToolRouterError::Gateway(crate::error::GatewayError::InvalidResponse(m)))
            }
        }
    }
}

// =========================================================================
// In-Memory Protobuf Struct <-> Serde JSON Direct Conversion
// =========================================================================

/// Directly converts a [`prost_types::Struct`] into a [`serde_json::Value`].
///
/// Avoids intermediate JSON string encoding/decoding, preserving performance.
pub fn prost_struct_to_json(s: prost_types::Struct) -> serde_json::Value {
    let mut map = serde_json::Map::with_capacity(s.fields.len());
    for (k, v) in s.fields {
        map.insert(k, prost_value_to_json(v));
    }
    serde_json::Value::Object(map)
}

/// Converts a [`prost_types::Value`] into its corresponding [`serde_json::Value`].
pub fn prost_value_to_json(v: prost_types::Value) -> serde_json::Value {
    match v.kind {
        Some(prost_types::value::Kind::NullValue(_)) | None => serde_json::Value::Null,
        Some(prost_types::value::Kind::NumberValue(n)) => serde_json::Number::from_f64(n)
            .map(serde_json::Value::Number)
            .unwrap_or(serde_json::Value::Null),
        Some(prost_types::value::Kind::StringValue(s)) => serde_json::Value::String(s),
        Some(prost_types::value::Kind::BoolValue(b)) => serde_json::Value::Bool(b),
        Some(prost_types::value::Kind::StructValue(s)) => prost_struct_to_json(s),
        Some(prost_types::value::Kind::ListValue(l)) => {
            serde_json::Value::Array(l.values.into_iter().map(prost_value_to_json).collect())
        }
    }
}

/// Directly converts a [`serde_json::Value`] object into a [`prost_types::Struct`].
///
/// Returns `None` if the input is not a JSON object (`Value::Object`).
pub fn json_to_prost_struct(val: &serde_json::Value) -> Option<prost_types::Struct> {
    let map = val.as_object()?;
    let mut fields = std::collections::BTreeMap::new();
    for (k, v) in map {
        fields.insert(k.clone(), json_to_prost_value(v));
    }
    Some(prost_types::Struct { fields })
}

/// Converts a [`serde_json::Value`] into its corresponding [`prost_types::Value`].
pub fn json_to_prost_value(val: &serde_json::Value) -> prost_types::Value {
    let kind = match val {
        serde_json::Value::Null => Some(prost_types::value::Kind::NullValue(0)),
        serde_json::Value::Bool(b) => Some(prost_types::value::Kind::BoolValue(*b)),
        serde_json::Value::Number(n) => {
            Some(prost_types::value::Kind::NumberValue(n.as_f64().unwrap_or(0.0)))
        }
        serde_json::Value::String(s) => Some(prost_types::value::Kind::StringValue(s.clone())),
        serde_json::Value::Array(arr) => {
            let values = arr.iter().map(json_to_prost_value).collect();
            Some(prost_types::value::Kind::ListValue(prost_types::ListValue { values }))
        }
        serde_json::Value::Object(map) => {
            let mut fields = std::collections::BTreeMap::new();
            for (k, v) in map {
                fields.insert(k.clone(), json_to_prost_value(v));
            }
            Some(prost_types::value::Kind::StructValue(prost_types::Struct { fields }))
        }
    };
    prost_types::Value { kind }
}

